'use client'

import { FormEvent, useEffect, useState } from 'react'
import { BriefcaseBusiness, ExternalLink, Plus, Trash2 } from 'lucide-react'

type Opportunity = { id:string; title:string; opportunity_type:string; organisation:string; deadline:string|null; source_url:string; is_published:boolean }
const TYPES = ['internship', 'apprenticeship', 'fellowship', 'competition', 'course', 'volunteering', 'project']
const empty = { title:'', opportunity_type:'internship', organisation:'', location:'', eligibility:'', summary:'', application_url:'', source_url:'', deadline:'', is_published:false }

export default function AdminOpportunitiesPage() {
  const [items,setItems]=useState<Opportunity[]>([]), [form,setForm]=useState(empty), [message,setMessage]=useState(''), [saving,setSaving]=useState(false)
  const field='rounded-lg border border-gray-700 bg-gray-900 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500'
  const load=()=>fetch('/api/admin/opportunities',{cache:'no-store'}).then(r=>r.json()).then(data=>Array.isArray(data)?setItems(data):setMessage(data.error||'Could not load opportunities'))
  useEffect(()=>{load()},[])
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setMessage('');const response=await fetch('/api/admin/opportunities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await response.json();setSaving(false);if(!response.ok)return setMessage(data.error||'Could not save opportunity');setForm(empty);setMessage('Opportunity saved.');load()}
  async function toggle(item:Opportunity){setMessage('');const response=await fetch(`/api/admin/opportunities/${item.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_published:!item.is_published})});const data=await response.json().catch(()=>({}));if(!response.ok)return setMessage(data.error||'Could not update publication status.');setMessage(item.is_published?'Opportunity moved to draft.':'Opportunity published.');load()}
  async function remove(id:string){if(!window.confirm('Delete this opportunity?'))return;setMessage('');const response=await fetch(`/api/admin/opportunities/${id}`,{method:'DELETE'});const data=await response.json().catch(()=>({}));if(!response.ok)return setMessage(data.error||'Could not delete opportunity.');setMessage('Opportunity deleted.');load()}
  return <div className="p-8 text-gray-100"><div className="mb-6"><h1 className="flex items-center gap-2 text-2xl font-bold"><BriefcaseBusiness className="h-6 w-6 text-cyan-400"/>Skills & Opportunities</h1><p className="mt-1 text-sm text-gray-400">Publish only direct, official opportunities that students can still apply for.</p></div>
    <form onSubmit={submit} className="mb-8 grid gap-3 rounded-xl border border-gray-700 bg-gray-800 p-5 md:grid-cols-2"><input required className={field} placeholder="Opportunity title *" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select className={field} value={form.opportunity_type} onChange={e=>setForm({...form,opportunity_type:e.target.value})}>{TYPES.map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</select><input required className={field} placeholder="Organisation *" value={form.organisation} onChange={e=>setForm({...form,organisation:e.target.value})}/><input className={field} placeholder="Location or Remote" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><label className="text-xs text-gray-400">Application deadline<input type="datetime-local" className={`mt-1 w-full ${field}`} value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></label><input className={field} placeholder="Eligibility (age, level, skills)" value={form.eligibility} onChange={e=>setForm({...form,eligibility:e.target.value})}/><textarea required className={`${field} md:col-span-2`} placeholder="Short, factual summary *" value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/><input required type="url" className={`${field} md:col-span-2`} placeholder="Official application URL *" value={form.application_url} onChange={e=>setForm({...form,application_url:e.target.value})}/><input required type="url" className={`${field} md:col-span-2`} placeholder="Official source / announcement URL *" value={form.source_url} onChange={e=>setForm({...form,source_url:e.target.value})}/><label className="flex items-center gap-2 text-sm text-gray-300"><input type="checkbox" checked={form.is_published} onChange={e=>setForm({...form,is_published:e.target.checked})}/>Publish after verification</label><button disabled={saving} className="flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-bold disabled:opacity-60"><Plus className="h-4 w-4"/>{saving?'Saving…':'Add opportunity'}</button>{message&&<p className="md:col-span-2 text-sm text-amber-300">{message}</p>}</form>
    <div className="overflow-hidden rounded-xl border border-gray-700 bg-gray-800"><div className="border-b border-gray-700 px-5 py-4 font-bold">{items.length} opportunities</div>{items.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-gray-700/60 px-5 py-4 last:border-0"><div><p className="font-semibold text-white">{item.title}</p><p className="mt-1 text-xs text-gray-400">{item.opportunity_type} · {item.organisation}{item.deadline?` · closes ${new Date(item.deadline).toLocaleDateString()}`:' · rolling deadline'}</p></div><div className="flex items-center gap-2"><a href={item.source_url} target="_blank" rel="noopener noreferrer" className="rounded p-2 text-gray-400 hover:bg-gray-700 hover:text-white"><ExternalLink className="h-4 w-4"/></a><button onClick={()=>toggle(item)} className={`rounded px-3 py-1.5 text-xs font-bold ${item.is_published?'bg-emerald-900/60 text-emerald-300':'bg-gray-700 text-gray-300'}`}>{item.is_published?'Published':'Draft'}</button><button onClick={()=>remove(item.id)} className="rounded p-2 text-gray-400 hover:bg-gray-700 hover:text-red-400"><Trash2 className="h-4 w-4"/></button></div></div>)}{!items.length&&<p className="py-12 text-center text-sm text-gray-500">No opportunities added yet.</p>}</div>
  </div>
}
