import type { Metadata } from 'next'
import Link from 'next/link'
import { AlertTriangle, Calendar, ExternalLink, Search, ShieldCheck, Sparkles } from 'lucide-react'
import { createServerSupabaseClient } from '@/lib/supabase'

export const dynamic = 'force-dynamic'
export const metadata: Metadata = { title: 'Internships & Student Opportunities Nepal', description: 'Find verified internships, fellowships, competitions, courses and volunteering opportunities for students in Nepal.' }
type Opportunity = { id:string; title:string; opportunity_type:string; organisation:string; location:string|null; eligibility:string|null; summary:string; application_url:string; source_url:string|null; deadline:string|null; is_verified:boolean; last_verified_at:string|null }
const TYPES:Record<string,string>={internship:'Internships',apprenticeship:'Apprenticeships',fellowship:'Fellowships',competition:'Competitions',course:'Short courses',volunteering:'Volunteering',project:'Project challenges'}
const clean=(value?:string)=>(value||'').replace(/[,().%]/g,' ').replace(/\s+/g,' ').trim().slice(0,80)
const validUrl=(value?:string|null)=>{if(!value)return null;try{const url=new URL(value);return ['http:','https:'].includes(url.protocol)?url.toString():null}catch{return null}}
const validDate=(value?:string|null)=>Boolean(value&&Number.isFinite(new Date(value).getTime()))
const date=(value:string|null)=>validDate(value)?new Intl.DateTimeFormat('en-NP',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value!)):'Rolling / see source'
const deadlineState=(value:string|null)=>{if(!validDate(value))return {days:null,label:'Rolling / date pending',tone:'text-slate-600',open:true};const end=new Date(value!);const now=new Date();end.setHours(0,0,0,0);now.setHours(0,0,0,0);const days=Math.round((end.getTime()-now.getTime())/86400000);if(days<0)return {days,label:`Closed ${Math.abs(days)} day${Math.abs(days)===1?'':'s'} ago`,tone:'text-slate-500',open:false};if(days===0)return {days,label:'Closes today',tone:'text-red-700',open:true};if(days<=7)return {days,label:`${days} day${days===1?'':'s'} left`,tone:'text-red-700',open:true};return {days,label:`${days} days left`,tone:'text-slate-600',open:true}}
const checked=(value:string|null)=>{if(!validDate(value))return {label:'Verification date unavailable',fresh:false};const days=Math.max(0,Math.floor((Date.now()-new Date(value!).getTime())/86400000));return {label:days===0?'Checked today':days===1?'Checked yesterday':`Checked ${days} days ago`,fresh:days<=30}}

export default async function OpportunitiesPage({searchParams}:{searchParams:{q?:string;type?:string;status?:string;deadline?:string}}){
  const db=createServerSupabaseClient();const q=clean(searchParams.q);const type=searchParams.type&&TYPES[searchParams.type]?searchParams.type:'';const status=searchParams.status==='all'?'all':'open'
  let query=db.from('student_opportunities').select('id,title,opportunity_type,organisation,location,eligibility,summary,application_url,source_url,deadline,is_verified,last_verified_at').eq('is_published',true).order('deadline',{ascending:true,nullsFirst:false}).limit(120)
  if(q)query=query.or(`title.ilike.%${q}%,organisation.ilike.%${q}%,summary.ilike.%${q}%`);if(type)query=query.eq('opportunity_type',type);if(status==='open')query=query.or(`deadline.is.null,deadline.gte.${new Date().toISOString()}`)
  const {data,error}=await query;if(error)console.error('[opportunities:list]',{code:error.code,message:error.message});const items=(data||[]) as Opportunity[];const hasFilters=Boolean(q||type||status==='all')
  return <main className="min-h-screen bg-[#f8f7f3]"><section className="border-b border-[#e6e4df] bg-[#16233f] text-white"><div className="mx-auto max-w-6xl px-4 py-14 sm:px-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-200">Build experience while you study</p><h1 className="mt-3 max-w-3xl font-display text-4xl font-bold sm:text-5xl">Opportunities for Nepal&apos;s students</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-blue-100">Internships, fellowships, competitions, projects, volunteering and practical short courses—with direct links to the organiser.</p></div></section><div className="mx-auto max-w-6xl px-4 py-9 sm:px-6">
    <form className="-mt-14 mb-7 grid gap-3 rounded-xl border border-[#e6e4df] bg-white p-4 shadow-md md:grid-cols-[1fr_210px_190px_auto]" role="search"><label><span className="mb-1.5 block text-xs font-bold text-slate-600">Role, skill or organisation</span><span className="relative block"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input name="q" maxLength={80} defaultValue={q} placeholder="e.g. internship, coding" className="w-full rounded-lg border border-slate-200 py-3 pl-9 pr-3 text-sm"/></span></label><label><span className="mb-1.5 block text-xs font-bold text-slate-600">Opportunity type</span><select name="type" defaultValue={type} className="h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">All types</option>{Object.entries(TYPES).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-bold text-slate-600">Deadline</span><select name="status" defaultValue={status} className="h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="open">Open or rolling</option><option value="all">Include closed</option></select></label><button className="mt-auto h-11 rounded-lg bg-primary px-5 text-sm font-bold text-white">Find opportunities</button><div className="flex items-center gap-4 md:col-span-4">{hasFilters&&<Link href="/opportunities" className="text-sm font-bold text-primary">Clear filters</Link>}<Link href="/my-path" className="ml-auto text-sm font-bold text-slate-600 hover:text-primary">Use with My Path →</Link></div></form>
    <div className="mb-7 flex gap-3 rounded-xl border border-[#e6e4df] bg-white p-4 text-sm leading-6 text-slate-700"><ShieldCheck className="h-5 w-5 shrink-0 text-primary"/><p><strong>Apply safely:</strong> use the official link, confirm the deadline and never pay an unofficial person for selection. “Source checked” means we reviewed the link—not that SikshyaNepal guarantees acceptance.</p></div>
    {error?<section role="alert" className="rounded-xl border border-red-200 bg-red-50 p-6 text-red-800"><div className="flex gap-3"><AlertTriangle className="h-5 w-5 shrink-0"/><div><h2 className="font-bold">Opportunities could not be loaded</h2><p className="mt-1 text-sm">This is a temporary data problem, not an empty result. Please try again.</p></div></div></section>:<><div className="mb-4"><h2 className="font-display text-2xl font-bold text-ink">{hasFilters?'Matching opportunities':'Current opportunities'}</h2><p className="mt-1 text-sm text-slate-500">{items.length} source-backed opportunit{items.length===1?'y':'ies'}{status==='open'?' accepting applications or using a rolling date':''}</p></div>
    {items.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(item=>{const deadline=deadlineState(item.deadline);const verification=checked(item.last_verified_at);const applyUrl=validUrl(item.application_url);const sourceUrl=validUrl(item.source_url);return <article key={item.id} className={`flex flex-col rounded-xl border border-[#e6e4df] bg-white p-5 shadow-sm ${deadline.open?'':'opacity-75'}`}><div className="flex items-start justify-between gap-3"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#9a302c]">{TYPES[item.opportunity_type]||item.opportunity_type.replaceAll('_',' ')}</p><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${item.is_verified&&verification.fresh?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-800'}`}>{item.is_verified&&verification.fresh?'SOURCE CHECKED':'RECHECK ADVISED'}</span></div><h2 className="mt-2 font-display text-xl font-bold text-ink">{item.title}</h2><p className="mt-1 text-sm font-semibold text-primary">{item.organisation}{item.location?` · ${item.location}`:''}</p><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{item.summary}</p>{item.eligibility&&<p className="mt-3 text-xs leading-5 text-slate-500"><strong>Who should check:</strong> {item.eligibility}</p>}<div className="mt-auto pt-5"><div className="space-y-1 border-t border-[#e6e4df] pt-3 text-xs"><p className={`flex items-center gap-1 font-semibold ${deadline.tone}`}><Calendar className="h-3.5 w-3.5"/>{deadline.label}{item.deadline?` · ${date(item.deadline)}`:''}</p><p className={verification.fresh?'text-emerald-700':'text-amber-700'}>{verification.label}</p></div><div className="mt-4 flex flex-wrap items-center gap-3">{applyUrl?<a href={applyUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 rounded-lg bg-primary px-3 py-2 text-sm font-bold text-white">Apply officially <ExternalLink className="h-4 w-4"/></a>:<span className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-600">Application link unavailable</span>}{sourceUrl&&sourceUrl!==applyUrl&&<a href={sourceUrl} target="_blank" rel="noopener noreferrer" className="text-xs font-bold text-primary">Check source</a>}</div></div></article>})}</div>:<section className="rounded-xl border border-dashed border-[#cfcac1] bg-white p-10 text-center"><Sparkles className="mx-auto h-8 w-8 text-primary"/><h2 className="mt-4 font-display text-2xl font-bold">No verified matches yet</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-600">Try a broader type or keyword. New listings appear only after an official source is reviewed.</p>{hasFilters&&<Link href="/opportunities" className="mt-5 inline-flex rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white">See all open opportunities</Link>}</section>}</>}
  </div></main>
}
