'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, Compass, RotateCcw } from 'lucide-react'

type Area = 'IT'|'Management'|'Medical'|'Engineering'|'Nursing'|'Humanities'
const questions=[
  {key:'interest',title:'What interests you most?',options:[['technology','Building apps and solving digital problems'],['business','Business, money, and leading projects'],['science','Science, health, and understanding how things work'],['people','Helping people and improving communities'],['creative','Writing, ideas, communication, and society']]},
  {key:'style',title:'What type of work sounds most enjoyable?',options:[['practical','Practical projects and hands-on work'],['analysis','Analysis, research, and problem-solving'],['people','Working directly with people'],['creative','Creating, presenting, and communicating']]},
  {key:'strength',title:'Which school subject feels strongest?',options:[['math','Mathematics / computer studies'],['science','Science / biology'],['commerce','Account / economics'],['language','Languages / social studies']]},
] as const
const areas:Record<Area,{title:string;description:string;caution:string}>={
  IT:{title:'IT & Computing',description:'BCA, BIT, BSc CSIT, software and computing-focused programmes.',caution:'Check mathematics requirements; they differ by programme and university.'},
  Management:{title:'Management & Business',description:'BBA, BBS, BBM, accounting, finance and entrepreneurship pathways.',caution:'Compare curriculum, internships and professional pathways—not only the degree title.'},
  Medical:{title:'Medical & Health Sciences',description:'Health-science routes with strong science and practical-study demands.',caution:'Subject eligibility and competitive entrance requirements are essential.'},
  Engineering:{title:'Engineering & Technical Studies',description:'Engineering and technical programmes based on mathematics, science and applied problem-solving.',caution:'Confirm +2 subjects, entrance examination and council requirements.'},
  Nursing:{title:'Nursing & People-focused Care',description:'Nursing, care and people-centred professional study routes.',caution:'Confirm science background, entrance rules and professional council recognition.'},
  Humanities:{title:'Humanities, Law & Social Sciences',description:'Law, media, humanities, education and social-science programmes.',caution:'Review writing, fieldwork and professional progression for each programme.'},
}
const weights:Record<string,Partial<Record<Area,number>>>={
  technology:{IT:5,Engineering:3},business:{Management:5,IT:1},science:{Medical:4,Engineering:4,Nursing:2},people:{Nursing:4,Humanities:3,Management:1},creative:{Humanities:5,Management:1,IT:1},
  practical:{Engineering:3,Medical:3,Nursing:3,IT:2},analysis:{IT:3,Engineering:3,Medical:2,Management:1},creative_style:{Humanities:3,Management:2,IT:1},people_style:{Nursing:3,Humanities:2,Management:1},
  math:{IT:4,Engineering:4,Management:1},science_subject:{Medical:4,Engineering:3,Nursing:3},commerce:{Management:5},language:{Humanities:5,Management:1},
}
const answerLabels:Record<string,string>={technology:'digital problem-solving',business:'business and leadership',science:'science and health',people:'people-focused work',creative:'communication and ideas',practical:'hands-on learning',analysis:'analysis and research',math:'strength in mathematics/computing',science_subject:'strength in science/biology',commerce:'strength in account/economics',language:'strength in languages/social studies'}

function ranked(answers:Record<string,string>){
  const normalized=[answers.interest,answers.style==='people'?'people_style':answers.style==='creative'?'creative_style':answers.style,answers.strength==='science'?'science_subject':answers.strength]
  const scores=(Object.keys(areas) as Area[]).map(area=>({area,score:normalized.reduce((sum,key)=>sum+(weights[key]?.[area]||0),0)})).sort((a,b)=>b.score-a.score||a.area.localeCompare(b.area))
  return scores.slice(0,3).map((item,index)=>({...item,...areas[item.area],reason:normalized.filter(key=>(weights[key]?.[item.area]||0)>0).map(key=>answerLabels[key]).filter(Boolean).slice(0,2),rank:index+1}))
}

export default function ProgramFinderPage(){
  const[answers,setAnswers]=useState<Record<string,string>>({})
  const answered=questions.filter(question=>answers[question.key]).length
  const done=answered===questions.length
  const results=useMemo(()=>done?ranked(answers):[],[answers,done])
  const choose=(key:string,value:string)=>setAnswers(current=>({...current,[key]:value}))
  return <div className="min-h-screen bg-[#f8f7f3]"><section className="border-b border-gray-200 bg-white"><div className="mx-auto max-w-3xl px-4 py-12 sm:px-6"><p className="text-xs font-bold uppercase tracking-widest text-primary">Student tools</p><h1 className="mt-3 font-display text-3xl font-extrabold text-ink sm:text-4xl">What should I study?</h1><p className="mt-3 text-gray-500">Answer three questions to compare study areas, then explore real colleges and official programme requirements.</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100" aria-label={`${answered} of ${questions.length} questions answered`}><div className="h-full rounded-full bg-primary transition-all" style={{width:`${answered/questions.length*100}%`}}/></div></div></section><main id="main-content" className="mx-auto max-w-3xl px-4 py-8 sm:px-6"><div className="rounded-2xl border border-gray-200 bg-white p-5 sm:p-8">{questions.map((question,index)=><section key={question.key} className={index?'mt-8 border-t border-gray-100 pt-8':''}><p className="text-xs font-bold uppercase tracking-widest text-primary">Question {index+1} of {questions.length}</p><h2 className="mt-2 font-display text-xl font-bold text-ink">{question.title}</h2><div className="mt-4 grid gap-2">{question.options.map(([value,label])=><button type="button" aria-pressed={answers[question.key]===value} key={value} onClick={()=>choose(question.key,value)} className={`flex items-center justify-between gap-3 rounded-xl border p-4 text-left text-sm font-semibold transition-colors ${answers[question.key]===value?'border-primary bg-blue-50 text-primary':'border-gray-200 text-gray-600 hover:border-blue-300'}`}><span>{label}</span>{answers[question.key]===value&&<CheckCircle2 className="h-4 w-4 shrink-0"/>}</button>)}</div></section>)}<button type="button" onClick={()=>setAnswers({})} disabled={!answered} className="mt-8 inline-flex items-center gap-1.5 text-sm font-semibold text-gray-500 hover:text-primary disabled:opacity-40"><RotateCcw className="h-4 w-4"/>Start again</button></div>
    {!done&&<p className="mt-5 rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-900">Answer {questions.length-answered} more question{questions.length-answered===1?'':'s'} to see your study-area matches.</p>}
    {done&&<section className="mt-6" aria-labelledby="finder-results"><p className="text-xs font-bold uppercase tracking-widest text-primary">Your starting points</p><h2 id="finder-results" className="mt-2 font-display text-2xl font-bold text-ink">Three study areas worth exploring</h2><p className="mt-2 text-sm leading-6 text-slate-600">These are ranked from your answers. A close second or third result can be just as suitable after checking subjects, cost and career goals.</p><div className="mt-5 space-y-4">{results.map(result=><article key={result.area} className={`rounded-2xl border p-5 sm:p-6 ${result.rank===1?'border-blue-200 bg-[#0d1b3e] text-white':'border-gray-200 bg-white text-ink'}`}><div className="flex items-start justify-between gap-4"><div><p className={`text-xs font-bold uppercase tracking-widest ${result.rank===1?'text-blue-200':'text-primary'}`}>{result.rank===1?'Strongest match':`Alternative ${result.rank-1}`}</p><h3 className="mt-1 font-display text-xl font-bold">{result.title}</h3></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${result.rank===1?'bg-white/10 text-blue-100':'bg-blue-50 text-blue-700'}`}>Score {result.score}</span></div><p className={`mt-3 text-sm leading-6 ${result.rank===1?'text-blue-100/80':'text-slate-600'}`}>{result.description}</p><p className={`mt-3 text-xs leading-5 ${result.rank===1?'text-blue-100':'text-slate-500'}`}><strong>Why:</strong> {result.reason.join(' and ')}.</p><p className={`mt-2 text-xs leading-5 ${result.rank===1?'text-amber-200':'text-amber-800'}`}><strong>Check first:</strong> {result.caution}</p><Link href={`/colleges?level=bachelor&faculty=${encodeURIComponent(result.area)}`} className={`mt-5 inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold ${result.rank===1?'bg-white text-primary':'bg-primary text-white'}`}><Compass className="h-4 w-4"/>Explore matching colleges <ArrowRight className="h-4 w-4"/></Link></article>)}</div><p className="mt-5 text-xs leading-5 text-slate-500">This transparent preference matcher is not a career assessment or eligibility decision. Confirm subjects, GPA, entrance rules, fees and official notices before applying.</p></section>}
  </main></div>
}
