'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
export type ConsentChoice = { functional: boolean; analytics: boolean; marketing: boolean; decidedAt: string }
export const CONSENT_KEY = 'sn_cookie_consent_v1'
function save(choice: ConsentChoice) { localStorage.setItem(CONSENT_KEY, JSON.stringify(choice)); window.dispatchEvent(new CustomEvent('sn-consent-changed', { detail: choice })) }
export default function CookieConsent() {
  const [open,setOpen]=useState(false), [manage,setManage]=useState(false), [functional,setFunctional]=useState(false), [analytics,setAnalytics]=useState(false), [marketing,setMarketing]=useState(false)
  useEffect(()=>{ const shouldOpen=!localStorage.getItem(CONSENT_KEY);setOpen(shouldOpen);window.dispatchEvent(new CustomEvent('sn-cookie-dialog',{detail:{open:shouldOpen}}));const show=()=>{setManage(true);setOpen(true);window.dispatchEvent(new CustomEvent('sn-cookie-dialog',{detail:{open:true}}))}; window.addEventListener('sn-open-cookie-settings',show); return()=>window.removeEventListener('sn-open-cookie-settings',show)},[])
  const choose=(values:{functional:boolean;analytics:boolean;marketing:boolean})=>{save({...values,decidedAt:new Date().toISOString()});setOpen(false);window.dispatchEvent(new CustomEvent('sn-cookie-dialog',{detail:{open:false}}))}
  if(!open)return null
  return <section role="dialog" aria-modal="true" aria-labelledby="cookie-title" className="fixed inset-x-3 bottom-3 z-[250] mx-auto max-w-2xl rounded-2xl border border-gray-200 bg-white p-5 shadow-2xl sm:bottom-5 sm:p-6"><h2 id="cookie-title" className="font-display text-lg font-bold text-ink">Your privacy choices</h2><p className="mt-2 text-sm leading-6 text-gray-600">Essential cookies keep sign-in and security working. Optional services stay off unless you allow them. Read our <Link href="/cookies" className="font-bold text-primary underline">cookie policy</Link>.</p>{manage&&<div className="mt-4 space-y-3 rounded-xl bg-gray-50 p-4"><label className="flex items-start justify-between gap-4"><span><strong className="block text-sm text-ink">Essential</strong><span className="text-xs text-gray-500">Authentication, security and saved consent choice.</span></span><input type="checkbox" checked disabled aria-label="Essential cookies always active"/></label><label className="flex items-start justify-between gap-4"><span><strong className="block text-sm text-ink">Functional</strong><span className="text-xs text-gray-500">Optional notification services.</span></span><input type="checkbox" checked={functional} onChange={e=>setFunctional(e.target.checked)} aria-label="Allow functional cookies"/></label><label className="flex items-start justify-between gap-4"><span><strong className="block text-sm text-ink">Analytics</strong><span className="text-xs text-gray-500">Anonymous usage measurement to improve the site.</span></span><input type="checkbox" checked={analytics} onChange={e=>setAnalytics(e.target.checked)} aria-label="Allow analytics cookies"/></label><label className="flex items-start justify-between gap-4"><span><strong className="block text-sm text-ink">Advertising</strong><span className="text-xs text-gray-500">Google AdSense and its measurement.</span></span><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)} aria-label="Allow advertising cookies"/></label></div>}<div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>choose({functional:true,analytics:true,marketing:true})} className="rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white">Accept all</button><button onClick={()=>choose({functional:false,analytics:false,marketing:false})} className="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-bold text-ink">Reject optional</button>{manage?<button onClick={()=>choose({functional,analytics,marketing})} className="rounded-lg border border-primary px-4 py-2.5 text-sm font-bold text-primary">Save choices</button>:<button onClick={()=>setManage(true)} className="rounded-lg px-3 py-2.5 text-sm font-bold text-primary">Manage choices</button>}</div></section>
}
