'use client'

import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import { AlertCircle, Bookmark, Loader2, MapPin, School, Trash2 } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'

type SavedSchool = { school_id:string; school:{id:string;name:string;slug:string;district:string|null;local_level:string|null;verification_status:string}|null }

export default function SavedSchoolsPage(){const pathname=usePathname(),router=useRouter();
  const[items,setItems]=useState<SavedSchool[]>([]),[needsLogin,setNeedsLogin]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[removing,setRemoving]=useState('')
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError('');try{const response=await fetch('/api/saved-schools',{cache:'no-store',signal});if(response.status===401){setNeedsLogin(true);return}if(!response.ok)throw new Error('Your school shortlist could not be loaded.');const data=await response.json();setItems(Array.isArray(data)?data.filter(item=>item.school):[])}catch(reason){if(reason instanceof Error&&reason.name!=='AbortError')setError(reason.message)}finally{setLoading(false)}},[])
  useEffect(()=>{if(pathname==='/account/saved-schools'){router.replace('/account/saved?type=schools');return}const controller=new AbortController();void load(controller.signal);return()=>controller.abort()},[load,pathname,router])
  const remove=async(item:SavedSchool)=>{setRemoving(item.school_id);setError('');try{const response=await fetch(`/api/saved-schools/${item.school_id}`,{method:'DELETE'});if(!response.ok)throw new Error('This school could not be removed. Please try again.');setItems(current=>current.filter(saved=>saved.school_id!==item.school_id))}catch(reason){setError(reason instanceof Error?reason.message:'This school could not be removed.')}finally{setRemoving('')}}
  if(pathname==='/account/saved-schools')return <div className="py-12 text-center text-sm text-gray-500">Opening saved institutions…</div>;return <div className="mx-auto mt-7 max-w-4xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="flex items-center gap-2 font-display text-2xl font-extrabold text-ink"><School className="h-6 w-6 text-blue-600"/>Saved schools</h2><p className="mt-2 text-gray-500">Keep school options together while comparing location, grades and admissions.</p></div></div>
    {error&&<div role="alert" className="mt-6 flex items-start justify-between gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><span className="flex gap-2"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0"/>{error}</span><button onClick={()=>void load()} className="shrink-0 font-bold underline">Try again</button></div>}
    {loading?<div aria-busy="true" className="mt-8 flex items-center justify-center gap-2 rounded-2xl border bg-white p-12 text-sm text-gray-500"><Loader2 className="h-5 w-5 animate-spin"/>Loading your school shortlist…</div>:needsLogin?<div className="mt-8 rounded-2xl border bg-white p-8 text-center"><p>Sign in to see and save your school shortlist.</p><Link href="/account/login?next=%2Faccount%2Fsaved-schools" className="mt-4 inline-block rounded-xl bg-primary px-5 py-3 font-bold text-white">Sign in</Link></div>:<div className="mt-8 space-y-3">{items.map(item=>item.school&&<article key={item.school_id} className="flex items-center justify-between gap-4 rounded-xl border border-gray-200 bg-white p-5 transition hover:border-blue-200 hover:shadow-sm"><Link href={`/schools/${item.school.slug}`} className="min-w-0 flex-1"><strong className="text-ink hover:text-primary">{item.school.name}</strong><span className="mt-1 flex items-center gap-1 text-sm text-gray-500"><MapPin className="h-3 w-3 shrink-0"/>{[item.school.local_level,item.school.district].filter(Boolean).join(', ')||'Location pending'}</span></Link><div className="flex shrink-0 items-center gap-2"><Link href={`/schools/${item.school.slug}`} className="rounded-lg border border-gray-200 px-3 py-2 text-xs font-bold text-primary">View</Link><button type="button" onClick={()=>void remove(item)} disabled={removing===item.school_id} aria-label={`Remove ${item.school.name} from saved schools`} className="rounded-lg p-2 text-gray-400 hover:bg-red-50 hover:text-red-600 disabled:opacity-50">{removing===item.school_id?<Loader2 className="h-4 w-4 animate-spin"/>:<Trash2 className="h-4 w-4"/>}</button></div></article>)}{!items.length&&!error&&<div className="rounded-2xl border bg-white p-10 text-center"><Bookmark className="mx-auto h-9 w-9 text-gray-300"/><h2 className="mt-3 font-display text-xl font-bold text-ink">Your school shortlist is empty</h2><p className="mt-2 text-sm text-gray-500">Save schools from their profiles to keep realistic options together.</p><Link href="/schools" className="mt-5 inline-flex rounded-xl bg-primary px-5 py-3 text-sm font-bold text-white">Explore schools</Link></div>}</div>}
  </div>
}
