'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { AlertTriangle, Calculator, CheckCircle2, Copy, Info, Printer, RotateCcw, WalletCards } from 'lucide-react'

type Inputs = { years:number; tuition:number; admission:number; exam:number; books:number; transport:number; living:number; livingMonths:number; scholarship:number; budget:number; increase:number; buffer:number }
const initial:Inputs={years:4,tuition:0,admission:0,exam:0,books:0,transport:0,living:0,livingMonths:12,scholarship:0,budget:0,increase:5,buffer:8}
const cities:Record<string,{living:number;note:string}>={Kathmandu:{living:18000,note:'Starting estimate for room, food and daily living.'},Pokhara:{living:14000,note:'Central areas may cost more.'},Bharatpur:{living:12000,note:'Housing and transport vary.'},Biratnagar:{living:12000,note:'Edit this for your situation.'},Nepalgunj:{living:11000,note:'Edit this for your situation.'},Other:{living:10000,note:'Generic estimate—not a verified local price.'}}
const money=(n:number)=>new Intl.NumberFormat('en-NP',{style:'currency',currency:'NPR',maximumFractionDigits:0}).format(Math.max(0,n))

export default function CollegeCostCalculatorPage(){
  const [v,setV]=useState(initial); const [city,setCity]=useState('Kathmandu');const[copied,setCopied]=useState(false)
  const set=(key:keyof Inputs,value:string)=>setV(x=>{const raw=Math.max(0,Number(value)||0);const bounded=key==='years'?Math.min(10,Math.max(1,Math.round(raw))):key==='livingMonths'?Math.min(12,Math.max(1,Math.round(raw))):key==='increase'?Math.min(25,raw):key==='buffer'?Math.min(30,raw):Math.min(100_000_000,raw);return{...x,[key]:bounded}})
  const result=useMemo(()=>{
    let tuition=0; for(let year=0;year<v.years;year++) tuition+=v.tuition*Math.pow(1+v.increase/100,year)
    const exam=v.exam*v.years,books=v.books*v.years,transport=v.transport*v.years,recurring=exam+books+transport,living=v.living*v.livingMonths*v.years,base=tuition+recurring+living+v.admission,reserve=base*v.buffer/100
    const scholarship=Math.min(base,v.scholarship), baseline=Math.max(0,base-scholarship), expected=baseline+reserve, lower=baseline, upper=expected, monthly=expected/Math.max(1,v.years*12), gap=Math.max(0,monthly-v.budget)
    const completed=[v.tuition,v.exam,v.books,v.living].filter(Boolean).length
    const covered=v.budget>0?Math.min(100,v.budget/monthly*100):0
    return {tuition,exam,books,transport,living,reserve,scholarship,baseline,expected,lower,upper,monthly,gap,covered,completed,confidence:completed===4?'Planning-ready':completed>=2?'Partial estimate':'Early estimate'}
  },[v])
  const input='mt-1 w-full rounded-lg border border-[#d9d6cf] bg-white px-3 py-2.5 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20'
  const numberField=(label:string,key:keyof Inputs,placeholder?:string,help?:string)=><label><span className="text-sm font-bold">{label}</span><input type="number" inputMode="numeric" value={v[key]||''} onChange={e=>set(key,e.target.value)} placeholder={placeholder} className={input}/>{help&&<p className="mt-1 text-xs leading-5 text-slate-500">{help}</p>}</label>
  const copySummary=async()=>{const text=[`SikshyaNepal study-cost estimate (${v.years} years, ${city})`,`Entered-cost baseline after scholarship: ${money(result.baseline)}`,`Fund target with ${v.buffer}% contingency: ${money(result.expected)}`,`Average monthly saving target: ${money(result.monthly)}`,`Tuition: ${money(result.tuition)}`,`Living (${v.livingMonths} months/year): ${money(result.living)}`,`Confirmed scholarship: ${money(result.scholarship)}`,'Estimate only—confirm all fees with the institution.'].join('\n');try{await navigator.clipboard.writeText(text);setCopied(true);window.setTimeout(()=>setCopied(false),1800)}catch{setCopied(false)}}
  return <main className="min-h-screen bg-[#f8f7f3]">
    <section className="border-b border-[#e6e4df] bg-[#fcfbf8]"><div className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#9a302c]">Student tools</p><h1 className="mt-3 font-display text-4xl font-bold">Real cost of study planner</h1><p className="mt-3 max-w-3xl text-lg leading-8 text-slate-600">Plan a realistic cost range—not one false exact total—before your family commits.</p></div></section>
    <div className="mx-auto grid max-w-5xl gap-6 px-4 py-8 sm:px-6 lg:grid-cols-[1fr_350px]">
      <section className="rounded-xl border border-[#e6e4df] bg-white p-5 sm:p-7" aria-labelledby="cost-inputs"><div className="flex items-center justify-between gap-4"><div><h2 id="cost-inputs" className="font-display text-2xl font-bold">Build your estimate</h2><p className="mt-1 text-sm text-slate-500">Use written college fees where possible.</p></div><button onClick={()=>{setV(initial);setCity('Kathmandu')}} className="inline-flex min-h-11 items-center gap-1 rounded-lg px-3 text-sm font-bold text-slate-500 hover:bg-slate-50 hover:text-primary"><RotateCcw className="h-4 w-4"/>Reset</button></div>
        <div className="mt-6 grid gap-5 sm:grid-cols-2">
          <label><span className="text-sm font-bold">City or study location</span><select value={city} onChange={e=>setCity(e.target.value)} className={input}>{Object.keys(cities).map(c=><option key={c}>{c}</option>)}</select><p className="mt-1 text-xs leading-5 text-slate-500">{cities[city].note} <button type="button" onClick={()=>set('living',String(cities[city].living))} className="font-bold text-primary underline">Use NPR {cities[city].living.toLocaleString('en-NP')}/month assumption</button></p></label>
          <label><span className="text-sm font-bold">Programme duration (years)</span><input type="number" inputMode="numeric" min="1" max="10" value={v.years} onChange={e=>set('years',e.target.value)} className={input}/></label>
          {numberField('Current annual tuition','tuition','e.g. 180000','Confirm whether the quoted fee is annual, semester or full-course.')}
          {numberField('One-time admission / registration','admission','e.g. 25000')}{numberField('Annual exam, lab and university fees','exam','e.g. 20000')}{numberField('Annual books, devices and materials','books','e.g. 15000')}{numberField('Annual transport','transport','Optional')}{numberField('Monthly room, food and living cost','living','Optional')}{numberField('Living months each year','livingMonths',undefined,'Use fewer than 12 only if you will not pay these costs year-round.')}{numberField('Confirmed scholarship total','scholarship','Use only confirmed support')}{numberField('Expected annual tuition increase (%)','increase',undefined,'An assumption, not a prediction.')}{numberField('Unexpected-cost buffer (%)','buffer',undefined,'This creates the upper fund target; it is not a predicted price increase.')}{numberField("Family's comfortable monthly budget",'budget','Optional')}
        </div>
        <div className="mt-6 rounded-lg bg-[#f5f3ee] p-4 text-sm leading-6 text-slate-700"><Info className="mb-2 h-5 w-5 text-primary"/><strong>Before relying on this:</strong> ask whether tuition includes examination, laboratory, library, internship, university and registration charges. City figures are editable assumptions.</div>
      </section>
      <aside className="space-y-5" aria-label="Cost estimate results">
        <section id="cost-summary" className="rounded-xl bg-[#16233f] p-6 text-white" aria-live="polite"><div className="flex items-center justify-between"><Calculator className="h-6 w-6 text-blue-200"/><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${result.completed===4?'bg-emerald-400/20 text-emerald-200':'bg-amber-300/20 text-amber-100'}`}>{result.confidence}</span></div><p className="mt-5 text-sm font-bold text-blue-100">Fund target after scholarship</p><p className="mt-1 font-mono text-3xl font-extrabold">{money(result.expected)}</p><div className="mt-4 rounded-lg bg-white/10 p-3"><p className="text-xs text-blue-100">Entered baseline → with {v.buffer}% contingency</p><p className="mt-1 font-mono text-sm font-bold">{money(result.lower)} → {money(result.upper)}</p></div><dl className="mt-5 space-y-3 border-t border-white/15 pt-5 text-sm">{[['Tuition across course',result.tuition],['Admission / registration',v.admission],['Exam, lab & university fees',result.exam],['Books, devices & materials',result.books],['Transport across course',result.transport],[`Living (${v.livingMonths} months/year)`,result.living],['Unexpected-cost buffer',result.reserve]].map(([label,n])=><div key={label as string} className="flex justify-between gap-3"><dt className="text-blue-100/75">{label}</dt><dd className="font-bold">{money(n as number)}</dd></div>)}<div className="flex justify-between"><dt className="text-blue-100/75">Confirmed scholarship</dt><dd className="font-bold text-emerald-300">−{money(result.scholarship)}</dd></div><div className="flex justify-between border-t border-white/15 pt-3"><dt className="text-blue-100/75">Average monthly saving target</dt><dd className="font-bold">{money(result.monthly)}</dd></div></dl><div className="mt-5 grid grid-cols-2 gap-2 print:hidden"><button type="button" onClick={()=>void copySummary()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-white/10 text-xs font-bold hover:bg-white/15"><Copy className="h-3.5 w-3.5"/>{copied?'Copied':'Copy summary'}</button><button type="button" onClick={()=>window.print()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-white/10 text-xs font-bold hover:bg-white/15"><Printer className="h-3.5 w-3.5"/>Print</button></div></section>
        {result.completed<4&&<section className="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><AlertTriangle className="h-5 w-5"/><h2 className="mt-2 font-bold">Complete the important costs</h2><p className="mt-1">Add tuition, exam/lab fees, books/devices and living cost to improve this estimate.</p></section>}
        {v.budget>0&&<section className={`rounded-xl border p-5 text-sm leading-6 ${result.gap?'border-amber-200 bg-amber-50 text-amber-950':'border-emerald-200 bg-emerald-50 text-emerald-950'}`}>{result.gap?<WalletCards className="h-5 w-5"/>:<CheckCircle2 className="h-5 w-5"/>}<h2 className="mt-2 font-bold">Family budget view</h2><p className="mt-1">{result.gap?`The expected plan is about ${money(result.gap)} above your monthly budget. Your entered budget covers roughly ${Math.round(result.covered)}% of the monthly target.`:'The expected estimate fits your budget. Check the upper range too.'}</p></section>}
        <section className="rounded-xl border border-[#e6e4df] bg-white p-5 text-sm leading-6 text-slate-700"><h2 className="font-bold">Compare fairly</h2><p className="mt-1">Use the same assumptions for every college. Low tuition may not mean low total cost.</p><Link href="/compare" className="mt-3 inline-flex min-h-11 items-center font-bold text-primary">Compare colleges →</Link></section><Link href="/scholarships" className="block min-h-11 rounded-lg bg-primary px-4 py-3 text-center text-sm font-bold text-white">Find scholarships</Link>
      </aside>
    </div>
  </main>
}
