import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, BookOpenCheck, Calculator, CalendarDays, GraduationCap, HeartHandshake, School, Trophy } from 'lucide-react'

export const metadata: Metadata = { title: 'शिक्षा नेपाल – विद्यालय, कलेज, भर्ना र नतिजा', description: 'नेपालका विद्यालय, कलेज, भर्ना सूचना, नतिजा, छात्रवृत्ति र विद्यार्थी उपयोगी उपकरणहरू खोज्नुहोस्।', alternates: { canonical: '/ne', languages: { en: '/' } } }
const links = [
  { title: 'विद्यालय खोज्नुहोस्', text: 'ECD देखि कक्षा १० सम्मका विद्यालय, स्थान र प्रमाणित जानकारी।', href: '/schools', Icon: School },
  { title: 'कलेज र कार्यक्रम', text: '+2, स्नातक र स्नातकोत्तर कलेज तथा कार्यक्रम तुलना गर्नुहोस्।', href: '/colleges', Icon: GraduationCap },
  { title: 'भर्ना सूचना', text: 'खुला भर्ना, मिति, योग्यता र आधिकारिक स्रोत हेर्नुहोस्।', href: '/admissions', Icon: CalendarDays },
  { title: 'नतिजा र सूचना', text: 'विश्वविद्यालय तथा बोर्डका नतिजा र महत्वपूर्ण सूचना।', href: '/results', Icon: Trophy },
  { title: 'GPA क्यालकुलेटर', text: 'SEE र NEB GPA अनुमान गर्न आफ्नो ग्रेडहरू राख्नुहोस्।', href: '/tools/gpa-calculator', Icon: Calculator },
  { title: 'छात्रवृत्ति', text: 'छात्रवृत्तिका अवसर र अन्तिम मिति खोज्नुहोस्।', href: '/scholarships', Icon: BookOpenCheck },
  { title: 'मेरो बाटो', text: 'आफ्नो पढाइ, भर्ना र रोजाइलाई एउटै योजनामा राख्नुहोस्।', href: '/my-path', Icon: HeartHandshake },
]
export default function NepaliHomePage() { return <main className="min-h-screen bg-[#f8f7f3]"><section className="bg-[#0d1b3e] text-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><p className="text-sm font-bold tracking-wide text-blue-300">शिक्षा नेपाल</p><h1 className="mt-4 max-w-3xl font-display text-4xl font-extrabold leading-tight sm:text-5xl">नेपालको शिक्षासम्बन्धी जानकारी, एउटै ठाउँमा।</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-blue-100/80">विद्यालय, कलेज, भर्ना, नतिजा र छात्रवृत्तिका जानकारी आधिकारिक स्रोतसँग जाँचेर खोज्नुहोस्।</p><Link href="/schools" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-primary hover:bg-blue-50">विद्यालय खोज्नुहोस् <ArrowRight className="h-4 w-4" /></Link></div></section><section className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="mb-7"><h2 className="font-display text-2xl font-bold text-ink">तपाईंलाई के खोज्न मद्दत चाहिन्छ?</h2><p className="mt-2 text-gray-500">सही निर्णयका लागि स्रोत, मिति र संस्थाको विवरण जाँच्नुहोस्।</p></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{links.map(({ title, text, href, Icon }) => <Link key={href} href={href} className="group rounded-2xl border border-gray-200 bg-white p-6 transition hover:-translate-y-1 hover:border-primary hover:shadow-lg"><Icon className="h-7 w-7 text-primary" /><h3 className="mt-5 font-display text-xl font-bold text-ink group-hover:text-primary">{title}</h3><p className="mt-2 text-sm leading-6 text-gray-500">{text}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-primary">हेर्नुहोस् <ArrowRight className="h-4 w-4" /></span></Link>)}</div></section><section className="mx-auto max-w-7xl px-4 pb-12 sm:px-6"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-6 text-amber-950"><h2 className="font-bold">सुरक्षित रूपमा आवेदन दिनुहोस्</h2><p className="mt-2 text-sm leading-6">शुल्क र व्यक्तिगत विवरण केवल संस्थाको आधिकारिक वेबसाइट, सूचना वा कार्यालयमार्फत मात्र बुझाउनुहोस्। शंका लागेमा मूल सूचना फेरि जाँच्नुहोस्।</p></div></section></main> }
