import PolicyPage from '@/components/community/PolicyPage'

export default function PrivacyPage() {
  return <PolicyPage eyebrow="Legal & trust" title="Privacy policy" intro="We collect only the information needed to run SikshyaNepal, protect students and meet legal obligations.">
    <h2>Accounts and public names</h2><p>Community participation requires Google authentication. Other users see only your chosen public name. SikshyaNepal&apos;s authorised administrators can link that name to the authenticated account, including its email and account identifier, for moderation, security and lawful requests.</p>
    <h2>Security information</h2><p>For abuse prevention we may record account ID, action type, date and time, and a one-way fingerprint derived from limited request information such as IP address and browser user-agent. The raw IP is not stored in the community tables. Security events are scheduled to expire after 180 days unless longer preservation is reasonably required for an active safety investigation, dispute or legal duty.</p>
    <h2>How information is used</h2><ul><li>Provide accounts, saved tools and community features.</li><li>Detect spam, repeated abuse and attempts to evade restrictions.</li><li>Review reports, enforce rules, protect users and respond to valid legal process.</li></ul>
    <h2>Admission enquiries</h2><p>When you choose to contact a college through SikshyaNepal, we collect the name, phone number, optional email, programme interest and optional message you submit. We use this information only to record, route and follow up on that enquiry, and may share it with the college you selected so it can respond. Enquiry contact data is normally scheduled for deletion after 180 days unless it must be preserved for an active dispute, safety matter or legal duty. Do not submit citizenship numbers, marksheets, passwords or payment information.</p>
    <h2>Cookies, tracking and third parties</h2><p>Essential authentication and security storage works without optional consent. Google AdSense loads only when you allow advertising cookies. OneSignal loads when you actively request push notifications. A PDF may be displayed directly from its source or, when direct display fails, through Google Docs Viewer. These providers process technical request information under their own policies. See the cookie policy to control optional services.</p>
    <h2>Sharing and deletion</h2><p>We do not publish your Google identity or sell it. Information may be disclosed when legally required or necessary to address an immediate safety threat. You may request account or content deletion at privacy@sikshyanepal.com; some minimal records may be retained where law or an active investigation requires it.</p>
    <h2>Children</h2><p>Students should not publish personal contact or location information. A parent or guardian may contact safety@sikshyanepal.com about a child&apos;s data or safety concern.</p>
  </PolicyPage>
}
