import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import SchoolCard from '@/components/schools/SchoolCard'
import { createServerSupabaseClient } from '@/lib/supabase'
import type { School } from '@/types'
const titleCase = (value: string) => value.split('-').map(part => part.charAt(0).toUpperCase() + part.slice(1)).join(' ')
async function load(municipality: string) { const safe = decodeURIComponent(municipality).replace(/[^a-z0-9-]/gi, ''); const name = titleCase(safe); const { data } = await createServerSupabaseClient().from('schools').select('*').eq('status', 'active').ilike('local_level', `%${name}%`).order('verification_status', { ascending: false }).order('name').limit(200); return { name, schools: (data || []) as School[] } }
export async function generateMetadata({ params }: { params: { municipality: string } }): Promise<Metadata> { const name = titleCase(params.municipality); return { title: `Schools in ${name}, Nepal – ECD to Grade 10`, description: `Find verified ECD through Grade 10 schools in ${name}, Nepal. Check school profiles, ownership, facilities and official sources.`, alternates: { canonical: `/schools/municipality/${params.municipality}` } } }
export default async function MunicipalitySchoolsPage({ params }: { params: { municipality: string } }) { const { name, schools } = await load(params.municipality); if (!name) notFound(); return <main className="min-h-screen bg-[#f8f7f3]"><section className="border-b border-gray-200 bg-white"><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><nav className="text-sm text-gray-500"><Link href="/schools">Schools</Link> / {name}</nav><h1 className="mt-4 font-display text-3xl font-extrabold text-ink">Schools in {name}</h1><p className="mt-3 max-w-3xl text-gray-600">Browse ECD through Grade 10 schools in {name}. Verify official contact details and source information before applying.</p></div></section><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><Link href="/schools" className="inline-block rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-bold text-gray-700">Browse all schools</Link><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{schools.map(school => <SchoolCard key={school.id} school={school} />)}</div>{!schools.length && <p className="mt-6 rounded-2xl border border-dashed border-gray-300 bg-white p-12 text-center text-gray-500">No active school profiles are indexed for {name} yet.</p>}</div></main> }
