import type { Metadata } from 'next'
import Link from 'next/link'
import { AlarmClock, AlertTriangle, CalendarPlus, CheckCircle2, ExternalLink, Filter, ShieldCheck } from 'lucide-react'
import { createServerSupabaseClient } from '@/lib/supabase'

export const dynamic = 'force-dynamic'
export const metadata: Metadata = { title: 'Student Deadline Calendar Nepal', description: 'Track verified admission, entrance exam, scholarship, internship and student opportunity deadlines across Nepal.' }

type DeadlineType = 'admission' | 'exam' | 'scholarship' | 'opportunity'
type Deadline = { id:string; type:DeadlineType; title:string; organisation:string; deadline:string; href:string; source:string|null; level:string|null; checked:string|null }
const LABELS:Record<DeadlineType,string>={admission:'Admission',exam:'Entrance exam',scholarship:'Scholarship',opportunity:'Opportunity'}
const TONES:Record<DeadlineType,string>={admission:'bg-blue-50 text-blue-700',exam:'bg-violet-50 text-violet-700',scholarship:'bg-amber-50 text-amber-800',opportunity:'bg-emerald-50 text-emerald-700'}
const date=(value:string)=>new Intl.DateTimeFormat('en-NP',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(new Date(value))
const dayStart=(value:Date)=>new Date(value.getFullYear(),value.getMonth(),value.getDate()).getTime()
const validDate=(value:string)=>Number.isFinite(new Date(value).getTime())
const checkedLabel=(value:string|null)=>{
  if(!value||!validDate(value))return {text:'Official source linked',fresh:false}
  const days=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/86400000))
  if(days===0)return {text:'Checked today',fresh:true}
  if(days===1)return {text:'Checked yesterday',fresh:true}
  return {text:`Checked ${days} days ago`,fresh:days<=30}
}
const calendarLink=(item:Deadline)=>{const start=new Date(item.deadline);const end=new Date(start.getTime()+86400000);const compact=(d:Date)=>d.toISOString().slice(0,10).replaceAll('-','');return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(item.title)}&dates=${compact(start)}/${compact(end)}&details=${encodeURIComponent(`Deadline from SikshyaNepal. Verify before applying: ${item.source||item.href}`)}`}

export default async function DeadlinesPage({searchParams}:{searchParams:{type?:string;range?:string;level?:string}}){
  const db=createServerSupabaseClient()
  const [admissions,exams,scholarships,opportunities]=await Promise.all([
    db.from('admissions').select('id,title,slug,institution_name,education_level,application_deadline,source_url,last_verified_at').eq('status','published').not('application_deadline','is',null).order('application_deadline',{ascending:true}).limit(150),
    db.from('entrance_exams').select('id,title,exam_body,education_level,application_deadline,source_url,exam_url,last_verified_at').eq('status','published').not('application_deadline','is',null).order('application_deadline',{ascending:true}).limit(100),
    db.from('scholarships').select('id,title,provider_name,deadline,application_url,source_url,last_verified_at,education_levels').eq('is_active',true).not('deadline','is',null).order('deadline',{ascending:true}).limit(100),
    db.from('student_opportunities').select('id,title,organisation,opportunity_type,deadline,application_url,source_url,last_verified_at').eq('is_published',true).not('deadline','is',null).order('deadline',{ascending:true}).limit(100),
  ])
  let items:Deadline[]=[
    ...(admissions.data||[]).map(x=>({id:x.id,type:'admission' as const,title:x.title,organisation:x.institution_name||'Institution',deadline:x.application_deadline!,href:`/admissions/${x.slug}`,source:x.source_url,level:x.education_level,checked:x.last_verified_at})),
    ...(exams.data||[]).map(x=>({id:x.id,type:'exam' as const,title:x.title,organisation:x.exam_body||'Exam authority',deadline:x.application_deadline!,href:x.exam_url||x.source_url||'/entrance-exams',source:x.source_url,level:x.education_level,checked:x.last_verified_at})),
    ...(scholarships.data||[]).map(x=>({id:x.id,type:'scholarship' as const,title:x.title,organisation:x.provider_name||'Scholarship provider',deadline:x.deadline!,href:x.application_url||x.source_url||'/scholarships',source:x.source_url,level:x.education_levels?.join(', ')||null,checked:x.last_verified_at})),
    ...(opportunities.data||[]).map(x=>({id:x.id,type:'opportunity' as const,title:x.title,organisation:x.organisation,deadline:x.deadline!,href:x.application_url,source:x.source_url,level:x.opportunity_type,checked:x.last_verified_at})),
  ]
  const unavailable=[admissions.error&&'admissions',exams.error&&'entrance exams',scholarships.error&&'scholarships',opportunities.error&&'opportunities'].filter(Boolean) as string[]
  const now=dayStart(new Date()), range=searchParams.range||'30', rangeDays=range==='7'?7:range==='90'?90:30
  if(searchParams.type&&searchParams.type in LABELS)items=items.filter(x=>x.type===searchParams.type)
  if(searchParams.level)items=items.filter(x=>(x.level||'').toLowerCase().includes(searchParams.level!.toLowerCase()))
  items=items.filter(x=>validDate(x.deadline)).filter(x=>{const time=dayStart(new Date(x.deadline));return range==='past'?time<now&&time>=now-90*86400000:time>=now&&time<=now+rangeDays*86400000}).sort((a,b)=>range==='past'?new Date(b.deadline).getTime()-new Date(a.deadline).getTime():new Date(a.deadline).getTime()-new Date(b.deadline).getTime())
  return <main className="min-h-screen bg-[#f8f7f3]"><section className="border-b border-[#e6e4df] bg-white"><div className="mx-auto max-w-6xl px-4 py-12 sm:px-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#9a302c]">One calendar, fewer missed chances</p><h1 className="mt-2 font-display text-4xl font-bold text-ink sm:text-5xl">Student deadline centre</h1><p className="mt-3 max-w-2xl text-lg leading-8 text-slate-600">Admissions, entrance forms, scholarships and opportunities—sorted by what closes next.</p></div></section><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6">
    <form className="grid gap-3 rounded-xl border border-[#e6e4df] bg-white p-4 shadow-sm sm:grid-cols-3 lg:grid-cols-[1fr_1fr_1fr_auto]"><label><span className="mb-1.5 block text-xs font-bold text-slate-500">Deadline type</span><select name="type" defaultValue={searchParams.type||''} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-3 text-sm"><option value="">Everything</option>{Object.entries(LABELS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-bold text-slate-500">Time window</span><select name="range" defaultValue={range} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-3 text-sm"><option value="7">Next 7 days</option><option value="30">Next 30 days</option><option value="90">Next 3 months</option><option value="past">Recently missed</option></select></label><label><span className="mb-1.5 block text-xs font-bold text-slate-500">Study level</span><select name="level" defaultValue={searchParams.level||''} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-3 text-sm"><option value="">All levels</option><option value="+2">+2</option><option value="Bachelor">Bachelor</option><option value="Master">Master</option><option value="Diploma">Diploma</option></select></label><button className="mt-auto flex items-center justify-center gap-2 rounded-lg bg-primary px-5 py-3 text-sm font-bold text-white"><Filter className="h-4 w-4"/>Apply</button></form>
    {unavailable.length>0&&<div role="status" className="mt-5 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0"/><div><p className="font-bold">Some deadline sources are temporarily unavailable</p><p className="mt-0.5">Showing everything we could load. Missing: {unavailable.join(', ')}. Check again shortly.</p></div></div>}
    <div className="mt-8 flex items-end justify-between"><div><h2 className="font-display text-2xl font-bold text-ink">{range==='past'?'Recently missed':'Coming up'}</h2><p className="mt-1 text-sm text-slate-500">{items.length} deadline{items.length===1?'':'s'} found{range==='past'?' from the last 90 days':''}</p></div><Link href="/deadlines" className="text-sm font-bold text-primary">Reset</Link></div>
    {items.length?<div className="mt-4 overflow-hidden rounded-xl border border-[#e6e4df] bg-white">{items.map((item,index)=>{const days=Math.ceil((dayStart(new Date(item.deadline))-now)/86400000);const external=item.href.startsWith('http');const evidence=checkedLabel(item.checked);return <article key={`${item.type}-${item.id}`} className={`grid gap-4 p-5 sm:grid-cols-[100px_1fr_auto] sm:items-center ${index?'border-t border-[#e6e4df]':''}`}><div><p className={`text-2xl font-bold ${days>=0&&days<=7?'text-[#b42318]':'text-ink'}`}>{new Date(item.deadline).getDate()}</p><p className="text-xs font-bold uppercase text-slate-500">{new Date(item.deadline).toLocaleDateString('en-NP',{month:'short',year:'numeric'})}</p><p className={`mt-1 text-xs ${days>=0&&days<=7?'font-bold text-[#b42318]':'text-slate-500'}`}>{days===0?'Closes today':days>0?`${days} days left`:`Closed ${Math.abs(days)} day${Math.abs(days)===1?'':'s'} ago`}</p></div><div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide ${TONES[item.type]}`}>{LABELS[item.type]}</span><h3 className="mt-2 font-bold text-ink">{item.title}</h3><p className="mt-1 text-sm text-slate-500">{item.organisation}{item.level?` · ${item.level}`:''}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs"><span className="flex items-center gap-1 font-medium text-slate-700"><CheckCircle2 className="h-3.5 w-3.5 text-emerald-600"/>Deadline: {date(item.deadline)}</span><span className={`flex items-center gap-1 ${evidence.fresh?'text-emerald-700':'text-amber-700'}`}><ShieldCheck className="h-3.5 w-3.5"/>{evidence.text}</span>{item.source&&<a href={item.source} target="_blank" rel="noopener noreferrer" className="font-bold text-primary hover:underline">Official source</a>}</div></div><div className="flex flex-wrap gap-2 sm:justify-end"><a href={calendarLink(item)} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700"><CalendarPlus className="h-4 w-4"/>Add to calendar</a><Link href={item.href} target={external?'_blank':undefined} rel={external?'noopener noreferrer':undefined} className="inline-flex items-center gap-1 rounded-lg bg-primary px-3 py-2 text-xs font-bold text-white">View details <ExternalLink className="h-3.5 w-3.5"/></Link></div></article>})}</div>:<div className="mt-4 rounded-xl border border-dashed border-[#cfcac1] bg-white py-16 text-center"><AlarmClock className="mx-auto h-9 w-9 text-slate-300"/><h3 className="mt-3 font-bold text-ink">No deadlines in this window</h3><p className="mt-1 text-sm text-slate-500">{unavailable.length?'Some sources could not be checked. Try again shortly.':'Try the next 3 months or another deadline type.'}</p></div>}
    <p className="mt-5 text-xs leading-5 text-slate-500">Dates can change after publication. Always confirm on the official page before paying a fee or submitting an application.</p>
  </div></main>
}
