'use client'
import { useEffect,useState } from 'react'
import { CheckCircle2,Save } from 'lucide-react'

type Item={id:string;fee:number|null;fee_period:string;fee_academic_year:string|null;fee_source_url:string|null;fee_last_verified_at:string|null;program:{name:string;degree_level:string}|null}
const periods=[['unknown','Period not documented'],['monthly','Monthly'],['semester','Per semester'],['annual','Annual'],['total_program','Total programme'],['one_time','One-time']]

export default function CollegeProgramFees({collegeId}:{collegeId:string}){
  const[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(''),[message,setMessage]=useState('')
  useEffect(()=>{fetch(`/api/admin/colleges/${collegeId}/program-fees`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d)}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false))},[collegeId])
  const set=(id:string,key:keyof Item,value:string|number|null)=>setItems(all=>all.map(item=>item.id===id?{...item,[key]:value}:item))
  async function save(item:Item){setSaving(item.id);setMessage('');const response=await fetch(`/api/admin/colleges/${collegeId}/program-fees`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});const data=await response.json().catch(()=>({}));setSaving('');setMessage(response.ok?`${item.program?.name||'Programme'} fee evidence saved.`:data.error||'Fee evidence could not be saved.')}
  const field='min-h-11 w-full rounded-lg border border-gray-600 bg-gray-700 px-3 py-2 text-sm text-white outline-none focus:ring-2 focus:ring-blue-500'
  return <section className="mx-8 mb-10 max-w-4xl rounded-xl border border-gray-700 bg-gray-800 p-5 text-gray-100"><h2 className="text-lg font-bold text-white">Programme fee evidence</h2><p className="mt-1 text-sm leading-6 text-gray-400">Never publish a fee without its payment period. Add the intake year, source and date checked whenever possible.</p>{message&&<p role="status" className="mt-4 rounded-lg bg-gray-900 p-3 text-sm text-amber-200">{message}</p>}{loading?<p className="mt-5 text-sm text-gray-400">Loading programme fees…</p>:<div className="mt-5 space-y-4">{items.map(item=><article key={item.id} className="rounded-xl border border-gray-700 bg-gray-900/50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{item.program?.name||'Programme'}</h3><span className="text-xs text-gray-500">{item.program?.degree_level}</span></div><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs font-semibold text-gray-300">Fee amount (NPR)<input type="number" min="0" inputMode="numeric" value={item.fee??''} onChange={e=>set(item.id,'fee',e.target.value===''?null:Number(e.target.value))} className={field}/></label><label className="text-xs font-semibold text-gray-300">Payment period<select value={item.fee_period||'unknown'} onChange={e=>set(item.id,'fee_period',e.target.value)} className={field}>{periods.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs font-semibold text-gray-300">Academic year / intake<input value={item.fee_academic_year||''} onChange={e=>set(item.id,'fee_academic_year',e.target.value)} placeholder="2083/84" className={field}/></label><label className="text-xs font-semibold text-gray-300">Last checked<input type="date" value={item.fee_last_verified_at?.slice(0,10)||''} onChange={e=>set(item.id,'fee_last_verified_at',e.target.value)} className={field}/></label><label className="text-xs font-semibold text-gray-300 md:col-span-2">Official fee source<input type="url" value={item.fee_source_url||''} onChange={e=>set(item.id,'fee_source_url',e.target.value)} placeholder="https://" className={field}/></label></div><button onClick={()=>void save(item)} disabled={saving===item.id} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-lg bg-blue-600 px-4 text-sm font-bold text-white disabled:opacity-60">{saving===item.id?<Save className="h-4 w-4 animate-pulse"/>:<CheckCircle2 className="h-4 w-4"/>}{saving===item.id?'Saving…':'Save fee evidence'}</button></article>)}{!items.length&&<p className="rounded-lg border border-dashed border-gray-700 p-5 text-sm text-gray-400">No programmes are linked to this college yet. Link programmes before entering fees.</p>}</div>}</section>
}
