import type { Metadata } from 'next'
import Link from 'next/link'
import { AlertTriangle, BookOpen, CheckCircle2, Download, ExternalLink, FileQuestion, Search } from 'lucide-react'
import { createServerSupabaseClient } from '@/lib/supabase'
import type { OldQuestion, Syllabus } from '@/types'

export const dynamic = 'force-dynamic'
export const metadata: Metadata = { title: 'Syllabus and Old Question Papers Nepal', description: 'Find verified university syllabi and past question papers by program, semester and year.' }
type Resource = (Syllabus & { kind: 'syllabus' }) | (OldQuestion & { kind: 'question' })
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const clean=(value?:string)=>(value||'').replace(/[%_,().]/g,' ').replace(/\s+/g,' ').trim().slice(0,80)
const validUrl=(value?:string|null)=>{if(!value)return null;try{const url=new URL(value);return ['http:','https:'].includes(url.protocol)?url.toString():null}catch{return null}}
const freshness=(value?:string|null)=>{if(!value||!Number.isFinite(new Date(value).getTime()))return {label:'Verification date unavailable',fresh:false};const days=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/86400000));return {label:days===0?'Checked today':days===1?'Checked yesterday':`Checked ${days} days ago`,fresh:days<=90}}

export default async function StudyResources({searchParams}:{searchParams:{q?:string;type?:string;program?:string;university?:string}}){
  const db=createServerSupabaseClient();const q=clean(searchParams.q);const type=['syllabus','question'].includes(searchParams.type||'')?searchParams.type||'':'';const program=uuid.test(searchParams.program||'')?searchParams.program||'':'';const university=uuid.test(searchParams.university||'')?searchParams.university||'':''
  let syllabusQuery=db.from('syllabus').select('*,program:programs(name,slug),university:universities(name,short_name)').eq('is_published',true).order('created_at',{ascending:false}).limit(150)
  let questionQuery=db.from('old_questions').select('*,program:programs(name,slug),university:universities(name,short_name)').eq('is_published',true).order('year',{ascending:false}).limit(150)
  if(program){syllabusQuery=syllabusQuery.eq('program_id',program);questionQuery=questionQuery.eq('program_id',program)}if(university){syllabusQuery=syllabusQuery.eq('university_id',university);questionQuery=questionQuery.eq('university_id',university)}if(q){syllabusQuery=syllabusQuery.ilike('title',`%${q}%`);questionQuery=questionQuery.ilike('subject',`%${q}%`)}
  const [syllabus,questions,programs,universities]=await Promise.all([syllabusQuery,questionQuery,db.from('programs').select('id,name').order('name'),db.from('universities').select('id,name,short_name').order('name')])
  const unavailable=[syllabus.error&&'syllabi',questions.error&&'past questions'].filter(Boolean) as string[];const setupRequired=[syllabus.error,questions.error].some(problem=>problem?.code==='42703'||problem?.code==='42P01');if(unavailable.length)console.error('[study-resources:list]',{syllabus:syllabus.error,questions:questions.error})
  let resources:Resource[]=[...(!type||type==='syllabus'?((syllabus.data||[]).map(x=>({...x,kind:'syllabus' as const})) as Resource[]):[]),...(!type||type==='question'?((questions.data||[]).map(x=>({...x,kind:'question' as const})) as Resource[]):[])]
  resources=resources.filter(item=>validUrl(item.file_url)||validUrl(item.source_url))
  const hasFilters=Boolean(q||type||program||university)
  return <main className="min-h-screen bg-[#f8f7f3]"><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#9a302c]">Prepare with the right material</p><h1 className="mt-2 font-display text-4xl font-bold text-ink">Study resources</h1><p className="mt-3 leading-7 text-slate-600">Official syllabi and past question papers, organised by university, program, semester and year. Files are linked to a source—not anonymously uploaded.</p></div>
    <form className="mt-7 grid gap-3 rounded-xl border border-gray-200 bg-white p-4 md:grid-cols-4" role="search"><label><span className="mb-1.5 block text-xs font-bold text-slate-600">Title or subject</span><span className="relative block"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input name="q" maxLength={80} defaultValue={q} placeholder="e.g. Calculus" className="w-full rounded-lg border border-gray-200 py-3 pl-9 pr-3 text-sm"/></span></label><label><span className="mb-1.5 block text-xs font-bold text-slate-600">Resource type</span><select name="type" defaultValue={type} className="h-11 w-full rounded-lg border border-gray-200 bg-white px-3 text-sm"><option value="">Syllabus & questions</option><option value="syllabus">Syllabus only</option><option value="question">Past questions only</option></select></label><label><span className="mb-1.5 block text-xs font-bold text-slate-600">Program</span><select name="program" defaultValue={program} disabled={Boolean(programs.error)} className="h-11 w-full rounded-lg border border-gray-200 bg-white px-3 text-sm disabled:bg-gray-100"><option value="">All programs</option>{(programs.data||[]).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-bold text-slate-600">University</span><select name="university" defaultValue={university} disabled={Boolean(universities.error)} className="h-11 w-full rounded-lg border border-gray-200 bg-white px-3 text-sm disabled:bg-gray-100"><option value="">All universities</option>{(universities.data||[]).map(x=><option value={x.id} key={x.id}>{x.short_name||x.name}</option>)}</select></label><div className="flex items-center gap-4 md:col-span-4"><button className="rounded-lg bg-primary px-5 py-3 text-sm font-bold text-white">Find resources</button>{hasFilters&&<Link href="/study-resources" className="text-sm font-bold text-primary">Clear filters</Link>}<Link href="/my-path" className="ml-auto text-sm font-bold text-slate-600 hover:text-primary">Back to My Path →</Link></div></form>
    {unavailable.length>0&&<div role="status" className="mt-6 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0"/><div><p className="font-bold">{setupRequired?'Study Resources needs its database update':'Some resources are temporarily unavailable'}</p><p className="mt-1">{setupRequired?<>Apply <code>20260928_study_resources_hub.sql</code> in this Supabase project. Draft resources remain hidden until publishing controls are available.</>:<>Showing everything that loaded. Missing: {unavailable.join(', ')}.</>}</p></div></div>}
    {(programs.error||universities.error)&&<p role="status" className="mt-3 text-sm text-amber-800">One or more filter lists could not load. Resource cards remain available below.</p>}
    <div className="mt-8"><h2 className="text-xl font-bold text-ink">{hasFilters?'Matching resources':'Available resources'}</h2><p className="mt-1 text-sm text-slate-500">{resources.length} source-backed resource{resources.length===1?'':'s'}</p></div>{resources.length?<div className="mt-4 grid gap-4 md:grid-cols-2">{resources.map(item=>{const title=item.kind==='syllabus'?item.title:item.subject;const file=validUrl(item.file_url);const source=validUrl(item.source_url);const verified=freshness(item.last_verified_at);return <article key={`${item.kind}-${item.id}`} className="flex gap-4 rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${item.kind==='syllabus'?'bg-blue-50 text-blue-700':'bg-amber-50 text-amber-700'}`}>{item.kind==='syllabus'?<BookOpen className="h-5 w-5"/>:<FileQuestion className="h-5 w-5"/>}</div><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{item.kind==='syllabus'?'Official syllabus':`Past question${item.kind==='question'&&item.year?` · ${item.year}`:''}`}</p><h3 className="mt-1 font-bold text-ink">{title}</h3><p className="mt-1 text-sm text-slate-500">{item.program?.name||'Program not listed'} · {item.university?.short_name||item.university?.name||'University not listed'}{item.semester?` · ${item.semester}`:''}</p><div className="mt-4 flex flex-wrap items-center gap-3"><span className={`flex items-center gap-1 text-xs ${verified.fresh?'text-emerald-700':'text-amber-700'}`}><CheckCircle2 className="h-3.5 w-3.5"/>{verified.label}</span>{source&&<a href={source} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 text-xs font-semibold text-slate-500 hover:text-primary"><ExternalLink className="h-3.5 w-3.5"/>Official source</a>}{file?<a href={file} target="_blank" rel="noopener noreferrer" className="ml-auto flex items-center gap-1 text-sm font-bold text-primary"><Download className="h-4 w-4"/>Open file</a>:<span className="ml-auto text-xs font-semibold text-slate-500">Use source link</span>}</div></div></article>})}</div>:<div className="mt-4 rounded-xl border border-gray-200 bg-white py-16 text-center"><BookOpen className="mx-auto h-9 w-9 text-gray-300"/><h3 className="mt-3 font-bold text-ink">No matching resources</h3><p className="mt-1 text-sm text-gray-500">Try a broader program or university. Materials appear after their source is checked.</p>{hasFilters&&<Link href="/study-resources" className="mt-5 inline-flex rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white">See all resources</Link>}</div>}
    <p className="mt-6 text-xs leading-5 text-slate-500">Past papers help you understand format and practice—not predict future questions. Confirm the current syllabus with your university or institution.</p>
  </div></main>
}
