'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { AlertCircle, ArrowRight, BookOpenCheck, CalendarDays, CheckCircle2, Circle, ExternalLink, GraduationCap, HeartHandshake, Landmark, ListChecks, Loader2, RefreshCw, School, Sparkles } from 'lucide-react'
import { pathStages, pathTasks, type PathStage as Stage } from '@/lib/my-path'

type Task = { id?: string; task_key: string; title: string; is_completed: boolean }
type Recommendation = { id:string; type:'exam'|'scholarship'|'opportunity'; title:string; detail:string; deadline:string|null; href:string }
type PathData = { name: string; stage: Stage | null; tasks: Task[]; savedColleges: { college: { id: string; name: string; slug: string; location: string | null } | null }[]; savedSchools: { school: { id: string; name: string; slug: string; district: string | null; province: string | null } | null }[]; admissions: { id: string; title: string; slug: string; application_deadline: string | null; institution_name: string | null; education_level: string | null }[]; scholarships: { id: string; title: string; deadline: string | null; amount: string | null }[]; recommendations: Recommendation[]; unavailable: string[] }

const stageOptions: { value: Stage; label: string; description: string; icon: typeof School }[] = [
  { value: 'grade_10', ...pathStages.grade_10, icon: School },
  { value: 'plus_two', ...pathStages.plus_two, icon: BookOpenCheck },
  { value: 'bachelor', ...pathStages.bachelor, icon: GraduationCap },
  { value: 'graduate', ...pathStages.graduate, icon: Landmark },
  { value: 'parent', ...pathStages.parent, icon: HeartHandshake },
]

const stageLinks: Record<Stage, { href: string; label: string }[]> = {
  grade_10: [{ href: '/colleges?level=%2B2', label: 'Explore +2 colleges' }, { href: '/schools', label: 'Find a school' }, { href: '/tools/gpa-calculator', label: 'Calculate GPA' }],
  plus_two: [{ href: '/colleges', label: 'Find a college' }, { href: '/admissions?deadline=open', label: 'Track admissions' }, { href: '/scholarships', label: 'Find scholarships' }],
  bachelor: [{ href: '/careers', label: 'Explore career paths' }, { href: '/opportunities', label: 'Find experience' }, { href: '/scholarships', label: 'Find scholarships' }],
  graduate: [{ href: '/programs', label: 'Explore further study' }, { href: '/opportunities', label: 'Find opportunities' }, { href: '/careers', label: 'Plan a career route' }],
  parent: [{ href: '/schools', label: 'Find a school' }, { href: '/colleges', label: 'Find a college' }, { href: '/tools/college-cost-calculator', label: 'Plan costs together' }],
}

const date = (value: string | null) => value && Number.isFinite(new Date(value).getTime()) ? new Intl.DateTimeFormat('en-NP', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value)) : 'Date to be announced'

export default function MyPathPage() {
  const [data, setData] = useState<PathData | null>(null)
  const [loading, setLoading] = useState(true)
  const [needsLogin, setNeedsLogin] = useState(false)
  const [setupRequired, setSetupRequired] = useState(false)
  const [error,setError]=useState('')
  const [saving,setSaving]=useState('')
  const [editingStage,setEditingStage]=useState(false)

  const load = async () => {
    setError('');setLoading(true)
    try{const response = await fetch('/api/my-path',{cache:'no-store'});const result=await response.json().catch(()=>({}));setNeedsLogin(response.status===401);setSetupRequired(Boolean(result.setupRequired));if(!response.ok&&response.status!==401&&!result.setupRequired)throw new Error(result.error||'Your path could not load.');if(response.ok)setData(result)}catch(reason){setError(reason instanceof Error?reason.message:'Your path could not load. Check your connection and try again.')}finally{setLoading(false)}
  }

  useEffect(() => {
    // This is only a fast UI hint; the API remains the authority for authentication.
    const hasLocalSession = Object.keys(localStorage).some(key => /^sb-.*-auth-token$/.test(key))
    if (!hasLocalSession) {
      setNeedsLogin(true)
      setLoading(false)
      return
    }
    void load()
  }, [])
  const tasks = useMemo(() => {
    const templates = data?.stage ? pathTasks[data.stage] : []
    return templates.map((template) => ({ ...template, is_completed: data?.tasks.find((task) => task.task_key === template.key)?.is_completed || false }))
  }, [data?.stage, data?.tasks])
  const savedPlaces = useMemo(() => [
    ...((data?.savedColleges || []).flatMap((item) => item.college ? [{ type: 'college', id: item.college.id, name: item.college.name, slug: item.college.slug, place: item.college.location }] : [])),
    ...((data?.savedSchools || []).flatMap((item) => item.school ? [{ type: 'school', id: item.school.id, name: item.school.name, slug: item.school.slug, place: [item.school.district, item.school.province].filter(Boolean).join(', ') }] : [])),
  ], [data?.savedColleges, data?.savedSchools])

  const chooseStage = async (stage: Stage) => {
    if(saving)return;setSaving('stage');setError('');try{const response=await fetch('/api/my-path',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({stage})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Your stage could not be saved.');setEditingStage(false);await load()}catch(reason){setError(reason instanceof Error?reason.message:'Your stage could not be saved.')}finally{setSaving('')}
  }

  const toggleTask = async (task: { key: string; title: string; is_completed: boolean }) => {
    if(saving)return;const previous=data;setSaving(task.key);setError('');setData(current=>current?{...current,tasks:[...current.tasks.filter(item=>item.task_key!==task.key),{task_key:task.key,title:task.title,is_completed:!task.is_completed}]}:current);try{const response=await fetch('/api/my-path',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task:{key:task.key,completed:!task.is_completed}})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Your task could not be saved.')}catch(reason){setData(previous);setError(reason instanceof Error?reason.message:'Your task could not be saved.')}finally{setSaving('')}
  }

  if (loading) return <main id="main-content" className="mx-auto min-h-[60vh] max-w-6xl px-4 py-16" aria-busy="true"><div role="status" className="sr-only">Loading your private education path</div><div className="h-8 w-48 animate-pulse rounded bg-slate-200 motion-reduce:animate-none" /><div className="mt-5 h-44 animate-pulse rounded-2xl bg-slate-100 motion-reduce:animate-none" /></main>
  if (needsLogin) return <main id="main-content" className="mx-auto min-h-[65vh] max-w-xl px-4 py-16 text-center sm:py-20"><div className="rounded-2xl border border-[#e6e4df] bg-white p-7 shadow-sm sm:p-9"><Sparkles className="mx-auto h-9 w-9 text-primary" aria-hidden="true" /><p className="mt-4 text-xs font-bold uppercase tracking-[0.14em] text-[#9a302c]">Your private student dashboard</p><h1 className="mt-2 font-display text-3xl font-bold text-ink">Build your education path</h1><p className="mx-auto mt-3 max-w-md leading-7 text-slate-600">Sign in to keep your next three actions, saved colleges, deadlines and application progress together.</p><p className="mt-3 text-sm text-slate-500">Browsing schools, colleges and public resources never requires an account.</p><Link href="/account/login?next=%2Fmy-path" className="mt-6 inline-flex min-h-11 items-center justify-center rounded-lg bg-primary px-5 py-3 text-sm font-bold text-white hover:bg-primary-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2">Sign in to continue</Link></div></main>
  if (setupRequired) return <main className="mx-auto max-w-xl px-4 py-20 text-center"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-8"><h1 className="font-display text-2xl font-bold">My Path is nearly ready</h1><p className="mt-3 text-sm leading-6 text-amber-950">The student-planning database setup still needs to be applied. Your account and existing saved items are safe.</p></div></main>
  if(error&&!data)return <main className="mx-auto max-w-xl px-4 py-20 text-center"><AlertCircle className="mx-auto h-10 w-10 text-amber-600"/><h1 className="mt-4 font-display text-2xl font-bold">My Path could not load</h1><p role="alert" className="mt-2 text-sm text-slate-600">{error}</p><button onClick={()=>void load()} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 font-bold text-white"><RefreshCw className="h-4 w-4"/>Try again</button></main>

  return <main className="min-h-screen bg-[#f8f7f3] pb-16"><section className="border-b border-[#e6e4df] bg-[#fcfbf8]"><div className="mx-auto max-w-6xl px-4 py-12 sm:px-6"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-[#9a302c]"><span className="h-px w-7 bg-[#c93b37]" />Your personal plan</p><h1 className="mt-3 font-display text-4xl font-bold text-ink sm:text-5xl">My Path{data?.name ? `, ${data.name}` : ''}</h1><p className="mt-3 max-w-2xl text-lg leading-8 text-slate-600">A calm place to decide what matters next—without losing deadlines, shortlists or practical tasks.</p></div></section>
    <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6">
      {error&&<p role="alert" className="mb-5 flex items-start gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0"/>{error}</p>}
      {(data?.unavailable||[]).length>0&&<p role="status" className="mb-5 flex items-start gap-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0"/>Your private checklist is safe. Some live sections could not load: {data!.unavailable.join(', ')}. Refresh to try again.</p>}
      {!data?.stage || editingStage ? <section className="rounded-2xl border border-[#e6e4df] bg-white p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-display text-2xl font-bold">Where are you right now?</h2><p className="mt-2 text-sm text-slate-600">Choose the stage that should shape your actions and recommendations.</p></div>{data?.stage&&<button onClick={()=>setEditingStage(false)} className="text-sm font-bold text-slate-600 hover:text-primary">Cancel</button>}</div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{stageOptions.map(({ value, label, description, icon: Icon }) => <button disabled={saving==='stage'} aria-pressed={data?.stage===value} key={value} onClick={() => void chooseStage(value)} className={`group rounded-xl border p-4 text-left disabled:opacity-60 ${data?.stage===value?'border-primary bg-primary-50 ring-2 ring-primary/10':'border-[#e6e4df] hover:border-primary hover:bg-primary-50'}`}><Icon className="h-5 w-5 text-primary" /><p className="mt-4 font-bold text-ink">{label}</p><p className="mt-1 text-xs leading-5 text-slate-600">{description}</p>{data?.stage===value&&<span className="mt-3 inline-flex text-xs font-bold text-primary">Current stage</span>}</button>)}</div></section> : <>
        <div className="grid gap-6 lg:grid-cols-[1.45fr_0.9fr]"><section className="rounded-2xl bg-[#16233f] p-6 text-white sm:p-8"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[0.14em] text-blue-200">Your next three actions</p><span aria-live="polite" className="text-xs font-bold text-blue-100">{tasks.filter(task=>task.is_completed).length}/{tasks.length} complete</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10" role="progressbar" aria-label="Path progress" aria-valuemin={0} aria-valuemax={tasks.length} aria-valuenow={tasks.filter(task=>task.is_completed).length}><div className="h-full bg-emerald-300 transition-all" style={{width:`${tasks.length?tasks.filter(task=>task.is_completed).length/tasks.length*100:0}%`}}/></div><div className="mt-5 space-y-3">{tasks.map((task) => <div key={task.key} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/5 p-3 sm:p-4"><button disabled={Boolean(saving)} aria-pressed={task.is_completed} aria-label={`${task.is_completed?'Mark incomplete':'Mark complete'}: ${task.title}`} onClick={() => void toggleTask(task)} className="flex min-w-0 flex-1 items-start gap-3 text-left disabled:opacity-60"><span className="mt-0.5">{saving===task.key?<Loader2 className="h-5 w-5 animate-spin text-blue-200"/>:task.is_completed?<CheckCircle2 className="h-5 w-5 text-emerald-300"/>:<Circle className="h-5 w-5 text-blue-200"/>}</span><span className={task.is_completed ? 'text-blue-100 line-through' : 'text-white'}>{task.title}</span></button><Link href={task.href} className="shrink-0 rounded-lg bg-white/10 px-2.5 py-2 text-xs font-bold text-white hover:bg-white hover:text-[#16233f]">{task.action}</Link></div>)}</div><div className="mt-6 flex flex-wrap gap-2">{stageLinks[data.stage].map((link) => <Link key={link.href} href={link.href} className="rounded-lg bg-white px-3 py-2 text-sm font-bold text-[#16233f]">{link.label}</Link>)}</div></section>
          <section className="rounded-2xl border border-[#e6e4df] bg-white p-6"><div className="flex items-center gap-2"><ListChecks className="h-5 w-5 text-[#c93b37]" /><h2 className="font-display text-xl font-bold">Plan details</h2></div><div className="mt-4 rounded-xl bg-[#f5f3ee] p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Current stage</p><p className="mt-1 font-bold text-ink">{pathStages[data.stage].label}</p></div><p className="mt-4 text-sm leading-6 text-slate-600">Your plan is private to your account. We only save your chosen stage and checklist completion—not documents or marks.</p><button onClick={() => setEditingStage(true)} className="mt-6 text-sm font-bold text-primary hover:underline">Change my stage</button></section></div>
        <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-[#e6e4df] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#9a302c]">Keep moving</p><h2 className="mt-1 font-display text-2xl font-bold">Upcoming admissions</h2></div><CalendarDays className="h-6 w-6 text-primary" /></div><div className="mt-4 divide-y divide-[#e6e4df]">{data.admissions.map((admission) => <Link key={admission.id} href={`/admissions/${admission.slug}`} className="block py-3 hover:text-primary"><p className="font-semibold">{admission.title}</p><p className="mt-1 text-xs text-slate-500">{admission.institution_name || admission.education_level || 'Admission'} · Deadline {date(admission.application_deadline)}</p></Link>)}{!data.admissions.length && <p className="py-5 text-sm text-slate-500">No confirmed upcoming admissions yet. Check the deadline centre for all updates.</p>}</div><Link href="/deadlines" className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-primary">View all student deadlines <ArrowRight className="h-4 w-4" /></Link></section>
          <section className="rounded-2xl border border-[#e6e4df] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#9a302c]">Your shortlist</p><h2 className="mt-1 font-display text-2xl font-bold">Saved places</h2></div><HeartHandshake className="h-6 w-6 text-primary" /></div><div className="mt-4 divide-y divide-[#e6e4df]">{savedPlaces.slice(0, 4).map((item) => <Link key={`${item.type}-${item.id}`} href={`/${item.type === 'school' ? 'schools' : 'colleges'}/${item.slug}`} className="block py-3 hover:text-primary"><p className="font-semibold">{item.name}</p><p className="mt-1 text-xs text-slate-500">{item.place}</p></Link>)}{!savedPlaces.length && <p className="py-5 text-sm text-slate-500">Save schools or colleges as you browse to keep them together here.</p>}</div><div className="mt-4 flex flex-wrap gap-3 text-sm font-bold text-primary"><Link href="/account/saved" className="inline-flex items-center gap-1">Saved colleges <ArrowRight className="h-4 w-4"/></Link><Link href="/account/saved-schools" className="inline-flex items-center gap-1">Saved schools <ArrowRight className="h-4 w-4"/></Link></div></section></div>
        <section className="mt-6 rounded-2xl border border-[#e6e4df] bg-white p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#9a302c]">Selected for your stage</p><h2 className="mt-1 font-display text-2xl font-bold">Exams, funding and experience</h2><p className="mt-1 text-sm text-slate-500">Current verified items that fit where you are now.</p></div><Link href="/deadlines" className="text-sm font-bold text-primary">See complete calendar →</Link></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(data.recommendations||[]).map(item=>{const external=item.href.startsWith('http');return <Link key={`${item.type}-${item.id}`} href={item.href} target={external?'_blank':undefined} rel={external?'noopener noreferrer':undefined} className="group rounded-xl border border-[#e6e4df] p-4 hover:border-primary hover:bg-primary-50"><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-bold uppercase tracking-wide text-[#9a302c]">{item.type}</span>{external&&<ExternalLink className="h-3.5 w-3.5 text-slate-400"/>}</div><p className="mt-2 font-bold text-ink group-hover:text-primary">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.detail}</p><p className="mt-3 text-xs font-semibold text-slate-700">Deadline {date(item.deadline)}</p></Link>})}{!(data.recommendations||[]).length&&<p className="sm:col-span-2 lg:col-span-3 rounded-xl bg-slate-50 p-5 text-sm text-slate-500">No stage-matched deadlines are published yet. We will show them here as official notices are verified.</p>}</div></section>
      </>}
    </div>
  </main>
}
