import { CheckCircle2, ExternalLink, ShieldCheck } from 'lucide-react'
import { evidenceFreshness } from '@/lib/evidence-freshness'
import { safeExternalUrl } from '@/lib/college-display'

export type CollegeEvidence = { id:string; field_key:string; claim_summary:string; source_name:string; source_url:string; checked_at:string; confidence_score:number; verification_status:string }

const fieldLabel:Record<string,string>={affiliation:'Affiliation',programs:'Programmes',fee:'Fees',admission_deadline:'Admission deadline',scholarship:'Scholarship',result:'Result',facilities:'Facilities',contact:'Contact'}

export default function CollegeEvidenceLedger({items}:{items:CollegeEvidence[]}){
  if(!items.length)return null
  return <section className="rounded-xl border border-emerald-200 bg-white p-6" aria-labelledby="evidence-heading"><div className="flex items-start gap-3"><div className="rounded-lg bg-emerald-50 p-2 text-emerald-700"><ShieldCheck className="h-5 w-5"/></div><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Evidence ledger</p><h2 id="evidence-heading" className="mt-1 text-lg font-semibold text-gray-950">Sources behind key facts</h2><p className="mt-1 text-sm leading-6 text-gray-600">Each entry supports one specific claim. Confidence describes extraction quality, not college quality.</p></div></div><div className="mt-5 divide-y divide-gray-100">{items.map(item=>{const freshness=evidenceFreshness(item.field_key,item.checked_at);const sourceUrl=safeExternalUrl(item.source_url);return <article key={item.id} className="py-4 first:pt-0 last:pb-0"><div className="flex flex-wrap items-start justify-between gap-3"><div className="max-w-xl"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-bold uppercase tracking-wide text-gray-500">{fieldLabel[item.field_key]||item.field_key}</span><span className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-bold ${freshness.stale?'bg-amber-50 text-amber-800':'bg-emerald-50 text-emerald-700'}`}><CheckCircle2 className="h-3 w-3"/>{freshness.stale?'Verified earlier · recheck due':'Verified source'}</span></div><p className="mt-1 text-sm leading-6 text-gray-800">{item.claim_summary}</p><p className="mt-1 text-xs text-gray-500">Checked {new Date(item.checked_at).toLocaleDateString('en-NP',{day:'numeric',month:'long',year:'numeric'})} · review every {freshness.maxAgeDays} day{freshness.maxAgeDays===1?'':'s'} · extraction confidence {item.confidence_score}%</p></div>{sourceUrl?<a href={sourceUrl} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center gap-1 text-xs font-bold text-blue-700">{item.source_name}<ExternalLink className="h-3.5 w-3.5"/></a>:<span className="text-xs font-semibold text-gray-500">Source link unavailable</span>}</div></article>})}</div></section>
}
