'use client'
import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, CheckCircle2, ExternalLink, RefreshCw } from 'lucide-react'

type Row = { id:string; name:string; slug:string; province:string|null; district:string|null; programme_count:number; gaps:string[]; priority:number; last_verified_at:string|null }
type Report = { summary:{total:number;needs_attention:number;complete:number;gaps:Record<string,number>}; rows:Row[]; generated_at:string }

export default function CollegeDataQualityPage() {
  const [report, setReport] = useState<Report|null>(null); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [view, setView] = useState<'all'|'attention'|'complete'>('attention'); const [refreshing, setRefreshing] = useState(false)
  const loadReport = () => { setRefreshing(true); setError(''); fetch(`/api/admin/colleges/data-quality?t=${Date.now()}`, { cache:'no-store' }).then(async r => { const d=await r.json(); if(!r.ok) throw new Error(d.error); setReport(d) }).catch(e=>setError(e.message || 'Report unavailable')).finally(() => setRefreshing(false)) }
  useEffect(() => { loadReport() }, [])
  const visibleRows = useMemo(() => (report?.rows || []).filter(row => {
    const matchesView = view === 'all' || (view === 'attention' ? row.priority > 0 : row.priority === 0)
    const needle = query.trim().toLowerCase()
    return matchesView && (!needle || `${row.name} ${row.province || ''} ${row.district || ''}`.toLowerCase().includes(needle))
  }), [report, query, view])
  const exportCsv = () => {
    const header = ['College', 'Province', 'District', 'Programmes', 'Gaps', 'Last verified']
    const lines = visibleRows.map(row => [row.name, row.province || '', row.district || '', row.programme_count, row.gaps.join('; '), row.last_verified_at || ''].map(value => `"${String(value).replaceAll('"', '""')}"`).join(','))
    const blob = new Blob([[header.join(','), ...lines].join('\n')], { type: 'text/csv;charset=utf-8' })
    const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `college-data-quality-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url)
  }
  if (error) return <div className="p-8 text-red-300">{error}</div>
  if (!report) return <div className="p-8 text-gray-400">Preparing data-quality report…</div>
  return <div className="p-8 text-gray-100 max-w-7xl">
    <div className="flex flex-wrap items-center justify-between gap-3 mb-2"><div className="flex items-center gap-3"><Link href="/admin/colleges" className="text-gray-400 hover:text-white"><ArrowLeft className="w-5 h-5" /></Link><h1 className="text-2xl font-bold text-white">College data quality</h1></div><button onClick={loadReport} disabled={refreshing} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-gray-600 px-3 text-sm font-semibold text-gray-200 hover:bg-gray-800 disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${refreshing ? 'animate-spin' : ''}`} />{refreshing ? 'Refreshing…' : 'Refresh report'}</button></div>
    <p className="text-gray-400 text-sm mb-6">Read-only checklist for active college records. Fix the highest-priority rows first.</p>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-7">{[['Active colleges',report.summary.total,'text-white'],['Needs attention',report.summary.needs_attention,'text-yellow-300'],['Complete',report.summary.complete,'text-green-300']].map(([label,value,color])=><div key={String(label)} className="rounded-xl border border-gray-700 bg-gray-800 p-5"><div className="text-sm text-gray-400">{label}</div><div className={`text-3xl font-bold mt-1 ${color}`}>{value}</div></div>)}</div>
    <div className="mb-7 rounded-xl border border-gray-700 bg-gray-800 p-5"><h2 className="text-sm font-semibold text-gray-300">Most common gaps</h2><div className="mt-3 flex flex-wrap gap-2">{Object.entries(report.summary.gaps).sort(([,a],[,b])=>b-a).map(([gap,count])=><span key={gap} className="rounded-full bg-gray-900 px-3 py-1.5 text-xs text-gray-300">{gap}: <strong className="text-yellow-200">{count}</strong></span>)}{!Object.keys(report.summary.gaps).length&&<span className="text-sm text-green-300">All active college records meet the current checks.</span>}</div></div>
    <div className="rounded-xl border border-gray-700 bg-gray-800 overflow-hidden"><div className="px-5 py-4 border-b border-gray-700"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">College records</h2><div className="flex items-center gap-3"><span className="text-xs text-gray-500">Generated {new Date(report.generated_at).toLocaleString()}</span><button onClick={exportCsv} disabled={!visibleRows.length} className="rounded-lg border border-gray-600 px-3 py-2 text-xs font-bold text-gray-200 hover:bg-gray-700 disabled:opacity-40">Export CSV</button></div></div><div className="mt-4 flex flex-wrap gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search college or district" className="min-h-10 flex-1 rounded-lg border border-gray-600 bg-gray-900 px-3 text-sm text-white placeholder:text-gray-500" />{(['attention','all','complete'] as const).map(option=><button key={option} onClick={()=>setView(option)} className={`min-h-10 rounded-lg px-3 text-xs font-bold capitalize ${view===option?'bg-blue-600 text-white':'bg-gray-700 text-gray-300'}`}>{option === 'attention' ? 'Needs attention' : option}</button>)}</div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-700 text-left text-gray-400"><th className="px-5 py-3">College</th><th className="px-5 py-3">Programmes</th><th className="px-5 py-3">Last verified</th><th className="px-5 py-3">Gaps</th><th className="px-5 py-3">Action</th></tr></thead><tbody>{visibleRows.map(row=><tr key={row.id} className="border-b border-gray-700/50 align-top"><td className="px-5 py-4"><div className="font-medium text-white">{row.name}</div><div className="text-xs text-gray-500">{[row.district,row.province].filter(Boolean).join(', ') || 'Location missing'}</div></td><td className="px-5 py-4">{row.programme_count}</td><td className="px-5 py-4 text-xs text-gray-400">{row.last_verified_at ? new Date(row.last_verified_at).toLocaleDateString('en-NP') : 'Never'}</td><td className="px-5 py-4"><div className="flex flex-wrap gap-1">{row.gaps.length ? row.gaps.map(g=><span key={g} className="rounded-full bg-yellow-900/40 px-2 py-1 text-xs text-yellow-200">{g}</span>) : <span className="text-green-300 flex gap-1"><CheckCircle2 className="w-4 h-4"/>Complete</span>}</div></td><td className="px-5 py-4"><Link href={`/admin/colleges/${row.id}/edit`} className="text-blue-300 hover:text-white inline-flex items-center gap-1">Review <ExternalLink className="w-3 h-3"/></Link></td></tr>)}{!visibleRows.length&&<tr><td colSpan={5} className="px-5 py-10 text-center text-sm text-gray-500">No colleges match this view.</td></tr>}</tbody></table></div></div>
  </div>
}
