'use client'

import Link from 'next/link'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertCircle, CalendarDays, CheckCircle2, Download, ExternalLink, FileCheck2, ListChecks, Loader2, RefreshCw, Trash2 } from 'lucide-react'

type Admission = { id:string; title:string; slug:string; institution_name:string|null; application_open_at:string|null; application_deadline:string|null; education_level:string|null; source_url:string|null; verification_status:string|null; last_verified_at:string|null }
type Plan = { id:string; status:string; checklist:Record<string,boolean>; notes:string|null; admission:Admission }
type PlannerData = { plans:Plan[]; admissions:Admission[] }
const statuses = [{value:'not_started',label:'Not started'},{value:'documents_ready',label:'Documents ready'},{value:'applied',label:'Applied'},{value:'entrance',label:'Entrance stage'},{value:'enrolled',label:'Enrolled'}]
const checks = [{key:'official_notice',label:'Read the official notice and eligibility'},{key:'documents',label:'Have the required documents ready'},{key:'payment',label:'Confirm official fee and payment method'},{key:'deadline',label:'Add the deadline to your calendar'}]
const fmt=(date:string|null)=>date?new Intl.DateTimeFormat('en-NP',{day:'numeric',month:'short',year:'numeric'}).format(new Date(date)):'To be announced'
const completed=(plan:Plan)=>checks.filter(item=>plan.checklist?.[item.key]).length
function deadlineLabel(date:string|null){if(!date)return{text:'Date not announced',urgent:false};const days=Math.ceil((new Date(date).getTime()-Date.now())/86_400_000);if(days<0)return{text:'Deadline passed',urgent:true};if(days===0)return{text:'Closes today',urgent:true};if(days===1)return{text:'1 day left',urgent:true};return{text:`${days} days left`,urgent:days<=7}}

export default function AdmissionPlanner(){
  const[data,setData]=useState<PlannerData|null>(null),[login,setLogin]=useState(false),[setup,setSetup]=useState(false),[error,setError]=useState(''),[savingIds,setSavingIds]=useState<Set<string>>(new Set()),[savedId,setSavedId]=useState('')
  const load=useCallback(async()=>{setError('');try{const response=await fetch('/api/admission-planner',{cache:'no-store'});const result=await response.json().catch(()=>({}));setLogin(response.status===401);setSetup(Boolean(result.setupRequired));if(!response.ok&&!result.setupRequired&&response.status!==401)throw new Error(result.error||'Your planner could not be loaded.');if(response.ok)setData({plans:result.plans||[],admissions:result.admissions||[]})}catch(reason){setError(reason instanceof Error?reason.message:'Your planner could not be loaded. Check your connection and try again.')}},[])
  useEffect(()=>{void load()},[load])
  const save=async(plan:Partial<Plan>&{admission:Admission,status:string})=>{if(savingIds.has(plan.admission.id))return;const previous=data;const draft:Plan={id:plan.id||`pending-${plan.admission.id}`,status:plan.status,checklist:plan.checklist||{},notes:plan.notes||'',admission:plan.admission};setError('');setSavedId('');setSavingIds(current=>new Set(current).add(plan.admission.id));setData(current=>current?{...current,plans:[draft,...current.plans.filter(item=>item.admission?.id!==plan.admission.id)]}:current);try{const response=await fetch('/api/admission-planner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({admission_id:plan.admission.id,status:plan.status,checklist:plan.checklist||{},notes:plan.notes||''})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Your change could not be saved.');setSavedId(plan.admission.id);window.setTimeout(()=>setSavedId(current=>current===plan.admission.id?'':current),1800);await load()}catch(reason){setData(previous);setError(reason instanceof Error?reason.message:'Your change could not be saved. Please try again.')}finally{setSavingIds(current=>{const next=new Set(current);next.delete(plan.admission.id);return next})}}
  const removePlan=async(plan:Plan)=>{if(savingIds.has(plan.admission.id)||!window.confirm(`Remove “${plan.admission.title}” from your planner?`))return;const previous=data;setError('');setSavingIds(current=>new Set(current).add(plan.admission.id));setData(current=>current?{...current,plans:current.plans.filter(item=>item.admission?.id!==plan.admission.id)}:current);try{const response=await fetch(`/api/admission-planner?admission_id=${encodeURIComponent(plan.admission.id)}`,{method:'DELETE'});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'This application could not be removed.')}catch(reason){setData(previous);setError(reason instanceof Error?reason.message:'This application could not be removed.')}finally{setSavingIds(current=>{const next=new Set(current);next.delete(plan.admission.id);return next})}}
  const summary=useMemo(()=>{const plans=data?.plans.filter(plan=>plan.admission)||[];const tasks=plans.length*checks.length;const done=plans.reduce((total,plan)=>total+completed(plan),0);return{applications:plans.length,done,tasks,percent:tasks?Math.round(done/tasks*100):0}},[data])
  if(login)return <main id="main-content" className="mx-auto max-w-xl px-4 py-20 text-center"><h1 className="font-display text-3xl font-bold">Your admission planner</h1><p className="mt-3 text-slate-600">Sign in to save a private application checklist and progress tracker.</p><Link className="mt-6 inline-block rounded-lg bg-primary px-5 py-3 font-bold text-white" href="/account/login?next=%2Fadmissions%2Fplanner">Sign in</Link></main>
  if(setup)return <main id="main-content" className="mx-auto max-w-xl px-4 py-20 text-center"><div className="rounded-xl border border-amber-200 bg-amber-50 p-7"><h1 className="font-display text-2xl font-bold">Planner setup is pending</h1><p className="mt-2 text-sm text-amber-950">The required database migration has not yet been applied.</p></div></main>
  if(!data&&error)return <main id="main-content" className="mx-auto max-w-xl px-4 py-20 text-center"><AlertCircle className="mx-auto h-10 w-10 text-amber-600"/><h1 className="mt-4 font-display text-2xl font-bold">Your planner could not load</h1><p role="alert" className="mt-2 text-sm leading-6 text-slate-600">{error}</p><button onClick={()=>void load()} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 font-bold text-white"><RefreshCw className="h-4 w-4"/>Try again</button></main>
  if(!data)return <main id="main-content" aria-busy="true" className="mx-auto max-w-5xl px-4 py-16"><span className="sr-only">Loading admission planner</span><div className="h-40 animate-pulse rounded-xl bg-slate-100"/></main>
  const planned=new Set(data.plans.map(plan=>plan.admission?.id))
  const availableAdmissions=data.admissions.filter(admission=>!planned.has(admission.id))
  return <main id="main-content" className="min-h-screen bg-[#f8f7f3]"><section className="border-b border-[#e6e4df] bg-[#fcfbf8]"><div className="mx-auto max-w-5xl px-4 py-12"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#9a302c]">Student tools</p><h1 className="mt-3 font-display text-4xl font-bold">Admission planner</h1><p className="mt-3 max-w-2xl text-lg leading-8 text-slate-600">Track applications without uploading personal documents. Always use the institution&apos;s official notice for final requirements.</p></div></section><div className="mx-auto max-w-5xl px-4 py-8">
    {error&&<div role="alert" className="mb-5 flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0"/><span>{error}</span></div>}
    <section aria-label="Planner summary" className="mb-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-[#e6e4df] bg-white p-4"><strong className="text-2xl text-ink">{summary.applications}</strong><p className="text-sm text-slate-500">Applications tracked</p></div><div className="rounded-xl border border-[#e6e4df] bg-white p-4"><strong className="text-2xl text-ink">{summary.done}/{summary.tasks}</strong><p className="text-sm text-slate-500">Preparation tasks done</p></div><div className="rounded-xl border border-[#e6e4df] bg-white p-4"><strong className="text-2xl text-ink">{summary.percent}%</strong><p className="text-sm text-slate-500">Overall preparation</p></div></section>
    <section className="rounded-xl bg-[#16233f] p-5 text-white sm:p-6"><div className="flex items-center gap-2"><ListChecks className="h-5 w-5 text-blue-200"/><h2 className="font-display text-2xl font-bold">My applications</h2></div><div className="mt-5 space-y-4">{data.plans.map(plan=>plan.admission&&<div key={plan.admission.id} className="rounded-xl bg-white/10 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={`/admissions/${plan.admission.slug}`} className="font-bold hover:underline">{plan.admission.title}</Link><p className="mt-1 text-xs text-blue-100">Deadline: {fmt(plan.admission.application_deadline)} · {completed(plan)}/{checks.length} tasks ready</p></div><div className="flex items-center gap-2"><span className="min-w-16 text-right text-xs text-emerald-300" aria-live="polite">{savingIds.has(plan.admission.id)?'Saving…':savedId===plan.admission.id?'Saved':''}</span><select aria-label={`Application status for ${plan.admission.title}`} disabled={savingIds.has(plan.admission.id)} value={plan.status} onChange={event=>void save({...plan,status:event.target.value})} className="rounded-lg border border-white/20 bg-[#16233f] px-3 py-2 text-sm disabled:opacity-60">{statuses.map(status=><option key={status.value} value={status.value}>{status.label}</option>)}</select></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{checks.map(check=><label key={check.key} className="flex min-h-10 cursor-pointer items-start gap-2 rounded-lg p-2 text-sm text-blue-50 hover:bg-white/5"><input type="checkbox" disabled={savingIds.has(plan.admission.id)} checked={Boolean(plan.checklist?.[check.key])} onChange={()=>void save({...plan,checklist:{...plan.checklist,[check.key]:!plan.checklist?.[check.key]}})} className="mt-0.5 h-4 w-4"/>{check.label}</label>)}</div><div className="mt-4 flex flex-wrap gap-2 border-t border-white/10 pt-4">{plan.admission.source_url&&<a href={plan.admission.source_url} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-10 items-center gap-1.5 rounded-lg bg-white/10 px-3 text-xs font-bold hover:bg-white/20"><ExternalLink className="h-3.5 w-3.5"/>Official source</a>}{plan.admission.application_deadline&&<a href={`/api/admissions/${plan.admission.id}/calendar`} className="inline-flex min-h-10 items-center gap-1.5 rounded-lg bg-white/10 px-3 text-xs font-bold hover:bg-white/20"><Download className="h-3.5 w-3.5"/>Add deadline to calendar</a>}<button type="button" disabled={savingIds.has(plan.admission.id)} onClick={()=>void removePlan(plan)} className="ml-auto inline-flex min-h-10 items-center gap-1.5 rounded-lg px-3 text-xs font-bold text-red-200 hover:bg-red-500/10 disabled:opacity-60"><Trash2 className="h-3.5 w-3.5"/>Remove</button></div></div>)}{!data.plans.length&&<p className="text-sm text-blue-100">Add an admission below to begin your private plan.</p>}</div></section>
    <section className="mt-8"><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-primary"/><h2 className="font-display text-2xl font-bold">Upcoming admissions</h2></div><div className="mt-4 grid gap-4 sm:grid-cols-2">{availableAdmissions.map(admission=>{const deadline=deadlineLabel(admission.application_deadline);return <article key={admission.id} className="rounded-xl border border-[#e6e4df] bg-white p-5"><div className="flex items-start justify-between gap-3"><h3 className="font-bold">{admission.title}</h3><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-bold ${deadline.urgent?'bg-red-50 text-red-700':'bg-blue-50 text-blue-700'}`}>{deadline.text}</span></div><p className="mt-2 text-sm text-slate-600">{admission.institution_name||admission.education_level||'Admission'} · {fmt(admission.application_deadline)}</p><button disabled={savingIds.has(admission.id)} onClick={()=>void save({admission,status:'not_started',checklist:{},notes:''})} className="mt-4 inline-flex min-h-10 items-center gap-1 rounded-lg bg-primary px-3 py-2 text-sm font-bold text-white disabled:opacity-60">{savingIds.has(admission.id)?<Loader2 className="h-4 w-4 animate-spin"/>:<FileCheck2 className="h-4 w-4"/>}{savingIds.has(admission.id)?'Adding…':'Add to plan'}</button></article>})}{!availableAdmissions.length&&<p className="text-sm text-slate-500">No other published admissions are available to add right now.</p>}</div></section>
    <p className="mt-8 flex gap-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><CheckCircle2 className="h-5 w-5 shrink-0"/>Keep documents on your own device. SikshyaNepal only stores your checklist and application status.</p>
  </div></main>
}
